= CloudFormation: (AWS) Create System Property/Parameter
// Creates the table of contents - this value could be removed and passed in as an attribute from the build task BUT
// having the :toc: value in the adoc files is required for publishToConfluence to work correctly
// Not sure how placement will affect publishing to Confluence
ifndef::confluence[]
:toc: left
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::confluence[]
:toc:

include::{includedir}/version-control-warning.adoc[]
endif::[]

[CAUTION]
System Manager properties/parameter can be either GLOBAL _or_ REGIONAL. By Default properties _are_ regional. Additionally,
Aws has recently introduced "Cross-account" parameter sharing ... see https://aws.amazon.com/blogs/mt/introducing-parameter-store-cross-account-sharing/[here].

// Renders correctly in IDE
ifndef::deploy[]

[NOTE]
Be aware this process is exactly the same as link:../serverless/sls-aws-create-system-property.adoc[Serverless: (AWS) Create System Property/Parameter]
*_EXCEPT_* CloudFormation only has a single `Resources` block. It does not require the additional `resources` block that
Serverless uses.

[NOTE]
To view details on System Manager Parameters/Properties, see link:../../../../engineering/tooling/tooling-cloud-aws/tooling-aws-system-parameters.adoc[System Parameters]

endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]

[NOTE]
Be aware this process is exactly the same as {sl-ops-link-003-004-006}[Serverless: (AWS) Create System Property/Parameter]
*_EXCEPT_* CloudFormation only has a single `Resources` block. It does not require the additional `resources` block that
Serverless uses.

[NOTE]
To view details on System Manager Parameters/Properties, see {tl-tooling-link-022-028}[System Parameters]

endif::[]

[TIP]
System Manager properties/parameter are Aws Free Tier eligible for _Standard parameters_. If you need to secure parameters
within System manager, there will be a fee (see https://aws.amazon.com/systems-manager/pricing/[here]).

== System Manager Property/Parameter

[source, yaml]
----
Resources:
    ServiceAssumedRoleNameProperty:
        Type: AWS::SSM::Parameter
        Properties:
          Name: !Sub brr.tools.${ShortName}.assumed.external.role.name
          Description: !Sub Role assumed to publish ${ProjectName}
          DataType: text
          Tier: Standard
          Type: String
          Value: !Sub ${ProjectName}-${AWS::Region}-assumed-service-role
          Tags:
            Environment: build
----

[TIP]
Use the above as an example and copy/paste into a CloudFormation template and edit the values to suit your purpose.

// Renders correctly in IDE
ifndef::deploy[]
include::../../../../_includes/ops-iac-aws-nwywlf.adoc[]
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]
include::{includedir}/ops-iac-aws-nwywlf.adoc[]
endif::[]


