= CloudFormation: (AWS) Create CodePipeline
// Not sure how placement will affect publishing to Confluence
:toc: left

// Renders correctly in IDE
ifndef::deploy[]

[CAUTION]
Please be aware that to be able to create a CodePipeline job using IaC the executing role
will require the CodePipeline IAM permission (see link:aws-cf-create-codepipeline.adoc#_permissions_required[Permissions Required]


[NOTE]
Be aware this process is exactly the same as link:../serverless/sls-aws-create-codepipeline.adoc[Serverless: (AWS) Create CodePipeline]
*_EXCEPT_* CloudFormation only has a single `Resources` block. It does not require the additional `resources` block that
Serverless uses.

[NOTE]
To view details on CodePipeline see link:../../../../engineering/tooling/tooling-cloud-aws/tooling-aws-setup-code-pipeline.adoc[Setup: CodePipeline]

endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]

[CAUTION]
Please be aware that to be able to create a CodePipeline job using IaC the executing role
will require the CodePipeline IAM permission (see {sl-ops-link-003-001-005}#_permissions_required[Permissions Required]


[NOTE]
Be aware this process is exactly the same as {sl-ops-link-003-004-003}[Serverless: (AWS) Create CodePipeline]
*_EXCEPT_* CloudFormation only has a single `Resources` block. It does not require the additional `resources` block that
Serverless uses.

[NOTE]
To view details on CodePipeline see {tl-tooling-link-022-025}[Setup: CodePipeline]

endif::[]

.CloudFormation Template
[source, yaml]
----
Resources:
  CodeReplicationPipeline: # Configure REPLICATION pipeline for library
    Type: AWS::CodePipeline::Pipeline                                   # CF type
    DependsOn: # This CF REQUIRES that the role and jobs have been created previously
      - ServiceCodePipelineRole
      - CbDisasterRecoverySyncRepository
    Properties:
      Name: !Sub ${ProjectName}-replication-pipeline                    # Pipeline name that will be visible in Aws CloudPipeline
      RoleArn: !Sub ${ServiceCodePipelineRole.Arn}                      # Assign role with required permissions
      Stages:
        - Name: code-commit-checkout                                    # Stage name
          Actions: # Be aware if multiple actions are declared they DO NOT RUN in parallel, to execute in parallel the jobs must be configured that way.
            - Name: Source                                              # Action name
              Namespace: SourceVariables
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: "1"
                Provider: CodeCommit
              Configuration:
                RepositoryName: !Sub ${GitRepoName}                     # Repository that will be checked out
                OutputArtifactFormat: CODE_ZIP
                PollForSourceChanges: false
                BranchName: main
              OutputArtifacts:
                - Name: SourceArtifact
        - Name: replicate-to-alternate-region                           # Stage name
          Actions:
            - Name: replicate                                           # Action name
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CbDisasterRecoverySyncRepository      # CodeBuild job name
              RunOrder: 1
              InputArtifacts: # Where will this action get its input
                - Name: SourceArtifact                                  # The name of the OutputArtifact from the first action
      ArtifactStore:
        Type: S3
        Location: !Ref DeployBucket
----

== Permissions Required

[WARNING]
Look at example repo for actual policies; I know the below is not complete but is necessary in order for this to work. It
is intended to reflect that additional work is required in order to make everything flow correctly.

[CAUTION]
Other permissions may be required to fully execute, but below is _close_ to a minimum set of permissions to
allow for deployment.

[source, shell]
----
statement {
    actions   = [
      "codepipeline:GetPipeline",
      "codepipeline:GetPipelineExecution",
      "codepipeline:StopPipelineExecution",
      "codepipeline:ListPipelineExecutions"
    ]
    resources = ["*"]
    effect = "Allow"
}
----

// Renders correctly in IDE
ifndef::deploy[]
include::../../../../_includes/ops-iac-aws-nwywlf.adoc[]
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]
include::{includedir}/ops-iac-aws-nwywlf.adoc[]
endif::[]
