= CloudFormation: (AWS) Get system property

[CAUTION]
System Manager properties/parameter can be either GLOBAL _or_ REGIONAL. By Default properties _are_ regional. Additionally,
Aws has recently introduced "Cross-account" parameter sharing ... see https://aws.amazon.com/blogs/mt/introducing-parameter-store-cross-account-sharing/[here].

[NOTE]
Be aware this process is _VERY_ similar to link:../serverless/sls-aws-get-system-property.adoc[Serverless: (AWS) Get System Property/Parameter]

[NOTE]
To view details on System Manager Parameters/Properties, see link:../../../../engineering/cloud/infrastructure/aws/aws-system-parameters.adoc[System Parameters]

[TIP]
System Manager properties/parameter are Aws Free Tier eligible for _Standard parameters_. If you need to secure parameters
within System manager, there will be a fee (see https://aws.amazon.com/systems-manager/pricing/[here]).

== Retrieve system property

.To retrieve SSM within CloudFormation
[source, yaml]
----
Resources:
  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${AWS::StackName}-launch-template
      LaunchTemplateData:
        ImageId: '{{resolve:ssm:golden-ami:2}}' # CloudFormation get property
        InstanceType: t2.micro
----

* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references-ssm.html[CloudFormation: SSM]







