= CloudFormation: (AWS) Get system property
// Creates the table of contents - this value could be removed and passed in as an attribute from the build task BUT
// having the :toc: value in the adoc files is required for publishToConfluence to work correctly
// Not sure how placement will affect publishing to Confluence
ifndef::confluence[]
:toc: left
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::confluence[]
:toc:

include::{includedir}/version-control-warning.adoc[]
endif::[]

[CAUTION]
System Manager properties/parameter can be either GLOBAL _or_ REGIONAL. By Default properties _are_ regional. Additionally,
Aws has recently introduced "Cross-account" parameter sharing ... see https://aws.amazon.com/blogs/mt/introducing-parameter-store-cross-account-sharing/[here].

// Renders correctly in IDE
ifndef::deploy[]

[NOTE]
Be aware this process is _VERY_ similar to link:../serverless/sls-aws-get-system-property.adoc[Serverless: (AWS) Get System Property/Parameter]

[NOTE]
To view details on System Manager Parameters/Properties, see link:../../../../engineering/tooling/tooling-cloud-aws/tooling-aws-system-parameters.adoc[System Parameters]

endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]

[NOTE]
Be aware this process is _VERY_ similar to {sl-ops-link-003-004-007}[Serverless: (AWS) Get System Property/Parameter]

[NOTE]
To view details on System Manager Parameters/Properties, see {tl-tooling-link-022-028}[System Parameters]

endif::[]

[TIP]
System Manager properties/parameter are Aws Free Tier eligible for _Standard parameters_. If you need to secure parameters
within System manager, there will be a fee (see https://aws.amazon.com/systems-manager/pricing/[here]).

== Retrieve system property

.To retrieve SSM within CloudFormation
[source, yaml]
----
Resources:
  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${AWS::StackName}-launch-template
      LaunchTemplateData:
        ImageId: '{{resolve:ssm:golden-ami:2}}' # CloudFormation get property
        InstanceType: t2.micro
----

* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references-ssm.html[CloudFormation: SSM]


// Renders correctly in IDE
ifndef::deploy[]
include::../../../../_includes/ops-iac-aws-nwywlf.adoc[]
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]
include::{includedir}/ops-iac-aws-nwywlf.adoc[]
endif::[]




