= Configure Aws CLI (Quick Start)

To configure Aws CLI you can use the following file ...

* Linux
** Open Terminal
** Execute cd ~/ to ensure you are in the User Home directory
** Verify exists or create - mkdir `.aws`
** Verify exists or create - touch `.aws/config`
** Paste the file below
* MacOS
** Open Terminal / iTerm
** Execute cd ~/ to ensure you are in the User Home directory
** Verify exists or create - mkdir `.aws`
** Verify exists or create - touch `.aws/config`
** Paste the file below
* Windows
** Open CMD / PowerShell / Git Bash
** Navigate to User Home directory
** IF using Git Bash
*** Verify exists or create - mkdir `.aws`
*** Verify exists or create - touch `.aws/config`
*** Paste the file below

[CAUTION]
This file is specifically for X and Y environments. If you are not working in those environments please use this as an
example layout and update with your accounts, region, and details

[NOTE]
For more info on Aws CLI configuration please see the following
link:../cloud/infrastructure/aws/aws-setup-cli.adoc[Setup: Aws CLI] - This document will give you the full explanation of how to setup Aws CLI and the reasons behind it.

[source, shell]
----
[default]
region = us-west-2
output = json
sso_session = default
# tools
#sso_account_id = XXXXXXXXX
# np
#sso_account_id = XXXXXXXXX
# p
#sso_account_id = XXXXXXXXX
sso_role_name = ProjectAdmin
[sso-session default]
sso_start_url = https://d-XXXXXXXXX.awsapps.com/start#
sso_region = us-east-1
sso_registration_scopes = sso:account:access

########## Tools ##########
[profile tools-devo]
sso_session = default
sso_account_id = XXXXXXXXX
sso_role_name = DevOpsEngineer
[profile tools-pa]
sso_session = default
sso_account_id = XXXXXXXXX
sso_role_name = ProjectAdmin

########## Non-Prod ##########
[profile np-devo]
sso_session = default
sso_account_id = XXXXXXXXX
sso_role_name = DevOpsEngineer
[profile np-pa]
sso_session = default
sso_account_id = XXXXXXXXX
sso_role_name = ProjectAdmin
[profile np-voa]
sso_session = default
sso_account_id = XXXXXXXXX
sso_role_name = ViewOnlyAccess

########## Prod ##########
[profile devo]
sso_session = default
sso_account_id = XXXXXXXXX
sso_role_name = DevOpsEngineer
[profile pa]
sso_session = default
sso_account_id = XXXXXXXXX
sso_role_name = ProjectAdmin
[profile voa]
sso_session = default
sso_account_id = XXXXXXXXX
sso_role_name = ViewOnlyAccess
----

== Not what you were looking for?

* link:../cloud/infrastructure/aws/aws-setup-cli.adoc[Setup: Aws CLI]
* link:../cloud/infrastructure/aws/aws-cli.adoc[How To: Aws CLI Usage]



