= CI: CodeBuild

Continuous Integration (CI) using Aws CodeBuild is essentially the same as link:build-gradle-artifact.adoc[Artifact Build]
except that it is happening on a remote build server through programmatic execution.

== Expected Steps

It is expected there should be an executable step for at least each of the following ...

* unit tests
* integration tests
* build and deploy
* remove the build
* api smoke tests

Depending on the application resource needs and the desired function you may also need the following ...

* domain resource deploy
* app resource deploy
* domain resource remove
* app resource remove
* parallel test configuration

== Configure a CodeBuild step

To set up a CI step in CodeBuild see how to link:../../../engineering/cloud/infrastructure/aws/aws-setup-code-build.adoc[Setup: AWS CodeBuild].

[CAUTION]
CodeBuild step names should match the buildspec name. In example if you have a `buildspec-integration.yml` to run the
integration tests the step in CodeBuild should be named <SHORT-PROJECT-NAME>-<BUILDSPEC-NAME>-<BRANCH> thus resulting
configured build step name is `bglt-integration-test-main`.

== Parameterize build job

To use properties/parameters stored within Aws System Manager see link:build-ci-codebuild-properties.adoc[CI: CodeBuild property access]

== Not what you were looking for?

* link:../engineering/development/java/java-maven.adoc[Java: Maven]
* link:../../development/build/build-maven-artifact.adoc[Maven: Build Artifact]
* link:../../development/build/build-maven-troubleshooting.adoc[Maven: Troubleshooting]
* link:../engineering/development/java/java-gradle.adoc[Java: Gradle]
* link:../../development/build/build-gradle-artifact.adoc[Gradle: Build Artifact]
* link:../../development/build/build-gradle-troubleshooting.adoc[Gradle: Troubleshooting]
* link:../../development/build/build-dependencies-updates.adoc[Dependency Updates]
* link:../../development/build/build-logging.adoc[Build Logging]


