= lyp-service: Run Book Example
:toc:

This page is to cover how to run the lyp-service (?service) and basic troubleshooting of the application.

[WARNING]
All links to Aws will only open if you are already signed into the correct account

The lyp-service is a simple SNS/SQS based service that only requires being authenticated to Aws using the `aws sso login`
command that is hosting the application in order to successfully invoke.

[NOTE]
This should be the br_NP or br_P accounts

== Known Topics

When a topic is published the topic will then send a message on to the subscribing queues.


|===
|Topic Name |Description |How to execute

|?
|?
|aws sns publish --topic-arn arn:aws:sns:us-west-2:xxxxx:queue-topic-test --message ""
|===

[CAUTION]
SNS Topics are used for their greater flexibility to support the future possibility of having multiple subscribers. SNS
is additionally used to support the use of Dead Letter Queues which without SNS support would not function correctly.

=== Other potential responses

* This will happen when your local sso token has timed out
[source, shell]
----
Error when retrieving token from sso: Token has expired and refresh failed
----

* If your local Aws config is not pointing to the correct account you will see the following. I.e your signed into br-Tools trying to call an app deployed to br-NP
[source, shell]
----
An error occurred (AuthorizationError) when calling the Publish operation: User: arn:aws:sts::xxxxxxxxx:assumed-role/AWSReservedSSO_PojectAdmin_7d9a660d60a5c5d0/benjamin.rhine@benrhine.com is not authorized to perform: SNS:Publish on resource: arn:aws:sns:us-west-2:xxxxxxxxxx:queue-topic-test because no resource-based policy allows the SNS:Publish action
----

== Known Alert Topics

Currently, all alerts are configured to be sent to `benjamin.rhine@benrhine.com` - TODO these should be updated to a mailing list


|===
|Alert Topic |Description |Where to view

|?
|?
|?
|===

== Known Queues

[WARNING]
When directly publishing to the queue the DLQ will not function. I.e. you can not trigger/test any errors when publishing this way.

[WARNING]
Not recommended to execute this way

|===
|Queue |Description |How to execute

|?
|?
|aws sqs send-message --queue-url
|===

== How to read the logs

Logs for this application are in JSON format to better support CloudWatch Logs Insights and to prevent any weirdness
with java multiline logs statements. By default `dev`, and `test`, are set to `DEBUG` while stage  and prod are set to
`INFO`. Each line is expandable to view the full log. To view the specific message from the application look for the
"*message*" key which will contain what the developer intended the application to output.

[CAUTION]
For details on how to leverage CloudWatch Insights see here.

== Log Startup

If you are viewing a log like on the right that means you are viewing an initialization log. This only captures
information right as the lambda starts up and will not contain logs from the actual lambda invocation.

[CAUTION]
While included in the same location within CloudWatch, startup log files are separate from execution log files.

== Log Runs

Each lambda execution will appear in the logs with the following *START* line ...

The line immediately following the *START* line is logging the event that the lambda received. I.E. this should contain anything and everything that you would care about being passed into the lambda

And will end with an *END* and *REPORT* ...

== Known Errors

=== Anything PKIX

While it is believed that all of these errors have been resolved there is some potential whenever a new cert is added or updated that something might not have been setup quite correctly and a PKIX error could be observed again.

This most likely means one of the following.

* cert is invalid or was not loaded correctly
* password is invalid or was not loaded correctly
* something is wrong with the body being posted to the requestor

Anything like this will more than likely need developer help to resolve.















