= Git: Hooks
// Creates the table of contents - this value could be removed and passed in as an attribute from the build task BUT
// having the :toc: value in the adoc files is required for publishToConfluence to work correctly
// Not sure how placement will affect publishing to Confluence
:toc: left

:keywords: engineering, tooling, git, hooks

// Renders correctly in IDE for testing purposes
// ifndef::confluence[]
// include::../_includes/version-control-warning.adoc[]
// endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::confluence[]
include::{includedir}/version-control-warning.adoc[]
endif::[]

// Renders correctly in IDE
ifndef::deploy[]
include::../../_includes/generic-information.adoc[]
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]
include::{includedir}/generic-information.adoc[]
endif::[]

== How are hooks installed?

ifndef::deploy[]

// These will only work from the file they are included in - NOT this file

Hooks can be installed by manually creating the file with the given name in a projects .git/hooks  directory. Sadly,
this directory is not under version control so some additional thought is required to ensure that everyone is adhering to
the same standard. For this reason on newer projects the hooks are maintained in the repo in the `.githooks` directory and
will be automatically installed on a per-project basis using Gradle (see link:../../engineering/development/build/build-gradle-git-hooks.adoc[here] for details).

endif::[]

ifdef::deploy[]

Hooks can be installed by manually creating the file with the given name in a projects .git/hooks  directory. Sadly,
this directory is not under version control so some additional thought is required to ensure that everyone is adhering to
the same standard. For this reason on newer projects the hooks are maintained in the repo in the `.githooks` directory and
will be automatically installed on a per-project basis using Gradle (see {sl-development-build-link-011}[here] for details).

endif::[]

== Check branch name for correctness (pre-commit hook)

One such check is to verify that the branch name meets expected team standards. This uses the pre-commit hook to check the branch name against a given regex.

== Prevent certain phrases from being committed (pre-commit hook)

As the title suggests this check will prevent certain phrases in the code from being committed such as if someone put a comment in the code that says "DO NOT COMMIT" then this check will disallow that commit until the text is removed.

Here is an example `pre-commit` hook that does both of the above

todo

== Prepend branch name to commit message (prepare-commit-msg hook)

Another hook which can be used is the prepare-commit-msg  hook and in this case it is being used to prepend the branch name (which should be the ticket name) to the commit message. This ensure that developers no longer forget to preface their commits with the ticket number they are working on.

todo

== Commit Message Template

To ensure good commit messages it is highly recommended to use a commit message template.

[CAUTION]
This requires that the devs use `git commit` NOT `git commit -m` as if you use the `-m` option the template will be ignored.

Skip hooks
Use either -n or --no-verify

----
git commit --no-verify -m "commit message"
           ^^^^^^^^^^^
-n
--no-verify
----

Prepend branch name in commit message

----
#!/bin/sh
#
# Automatically adds branch name and branch description to every commit message.
# Modified from the gist here https://gist.github.com/bartoszmajsak/1396344
# This way you can customize which branches should be skipped when
# prepending commit message.
RED="\033[1;31m"
GREEN="\033[1;32m"
ORANGE="\033[0;33m"
NOCOLOR="\033[0m"
if [ -z "$BRANCHES_TO_SKIP" ]; then
  BRANCHES_TO_SKIP=(master production staging)
fi
AUTHORINFO=$(git var GIT_AUTHOR_IDENT) || exit 1
NAME=$(printf '%s\n\n' "${AUTHORINFO}" | sed -n 's/^\(.*\) <.*$/\1/p')
# Regex to check the valid branch name
# For stricter enforcement change the alpha match to IDDS or the expected ticket prefix
VALID_BRANCH_REGEX="(^(feature|hotfix|bugfix|library|prerelease|release|dev|improvement)\/([A-Z]+\-[0-9]+))|^([A-Z]+\-[0-9]+)|^([A-Z]+\-[0-9]+\-*)|main$"
# Get branch name and description
# BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')
BRANCH_NAME="$(git rev-parse --abbrev-ref HEAD)"
#setting space as delimiter
IFS='-'
#reading str as an array as tokens separated by IFS
read -ra SPLIT <<<"$BRANCH_NAME"
BRANCH_NAME_SHORT="${SPLIT[0]}"-"${SPLIT[1]}"
unset IFS
# Check if branch is any of (feature|hotfix|bugfix|release|dev|improvement)
# This will only work for branches with a single slash in the path
if [[ "$BRANCH_NAME_SHORT" == *"/"* ]]
then
  # Alternate line split as IFS throws an error when its reset
  echo "Full branch name contains slash... calculating simple name "
  SPLIT2=($(echo $BRANCH_NAME_SHORT | tr "/" "\n"))
  BRANCH_NAME_SHORT="${SPLIT2[1]}"
fi
# Branch name should be excluded from the prepend
BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")
# A developer has already prepended the commit in the format BRANCH_NAME
BRANCH_IN_COMMIT=$(grep -c "$BRANCH_NAME_SHORT" $1)
# check the branch name is valid or not
if [[ "$BRANCH_NAME" =~ $VALID_BRANCH_REGEX ]]; then
  # if face any error in mac then run chmod u+x .git/hooks/prepare-commit-msg and restart your terminal
  if [ -n "$BRANCH_NAME" ] && ! [[ $BRANCH_EXCLUDED -eq 1 ]] && ! [[ $BRANCH_IN_COMMIT -ge 1 ]]; then
    if [[ "$BRANCH_NAME" == "main" ]]
    then
      # Don't add the "main" name to commits that go directly to main
      sed -i.bak -e "1s/^//" $1
    else
      # This command WILL NOT WORK RIGHT if there is a slash in BRANCH_NAME_SHORT
      sed -i.bak -e "1s/^/$BRANCH_NAME_SHORT: /" $1
    fi
  fi
else
  echo -e "\n${RED}Prepare-commit-msg: Please correct the branch name${NOCOLOR}"
  printf "\nBranch Name not as per the defined rules like:  "
  echo -e "${GREEN}feature, hotfix, bugfix, library, prerelease, release, dev, improvement, hotfix-102, XXXX-1234, XXXX-1234-something\n"
  echo -e "${ORANGE}You cannot push in these branches directly: ${BRANCHES_TO_SKIP[@]}\n"
  echo -e "${ORANGE}Current BRANCH_NAME: ${BRANCH_NAME}"
  echo -e "\n${RED}Oh, please stop. I cannot allow you to commit with your current branch: ${BRANCH_NAME}${NOCOLOR}"
  exit 1;
fi
----

Pre-commit with phrase filter

----
#!/bin/sh
# ANSI color codes.
RED="\033[1;31m"
GREEN="\033[1;32m"
ORANGE="\033[0;33m"
BLUE="\033[00;34m"
NOCOLOR="\033[0m"
########################################################################################################################
# Forbidden phrases.
########################################################################################################################
FORBIDDEN_PHRASES=("DNC" "DO NOT COMMIT" "TODO(PR)")
violation_output=""
# Go over the staged changes, and if any of the forbidden phrases is used,
# add an appropriate message to the output.
for forbidden_word in "${FORBIDDEN_PHRASES[@]}"; do
	changed_file_names=$(git diff --cached --name-only)
	for changed_file_name in $changed_file_names; do
		changed_file_content=$(git diff HEAD --no-ext-diff -U0 --exit-code -a --no-prefix $changed_file_name | egrep "^\+")
		if echo $changed_file_content | grep -q "$forbidden_word"; then
			violation_output+="${CLEAR} • ${BLUE}${changed_file_name}${CLEAR} contains ${RED}\"$forbidden_word\"${CLEAR}\n"
		fi
	done
done
# If there are any violations, print the output and exit with an error code.
if [[ ! -z $violation_output ]]; then
	printf "COMMIT REJECTED (DNC violation): see below for details\n"
	printf "$violation_output"
	exit 1
fi
########################################################################################################################
# End Forbidden phrases.
########################################################################################################################
########################################################################################################################
# Check branch name meets expected criteria.
########################################################################################################################
# Disallow committing directly to the following branches - These are prevented by not being included in the regex
if [ -z "$BRANCHES_TO_SKIP" ]; then
  BRANCHES_TO_SKIP=(master production staging)
fi
# Regex to check the valid branch name - for stricter enforcement change the alpha match to IDDS or the expected ticket prefix
# While this does allow branch creation it will not allow commits unless the branch name matches the following ...
#
# Valid branch names examples								Invalid branch names examples
# feature/IDDS-1234   											feature/idds-1234
# feature/IDDS-1234-test 										feature/idds-1234-test
# hotfix/IDDS-1234  												feature/1234
# hotfix/IDDS-1234-test
# ... 																			...
# IDDS-1234 																idds-1234
# IDDS-1234-test  													1234
VALID_BRANCH_REGEX="(^(feature|hotfix|bugfix|library|prerelease|release|dev|improvement)\/([A-Z]+\-[0-9]+))|^([A-Z]+\-[0-9]+)|^([A-Z]+\-[0-9]+\-*|main)$"
# Get branch name and description
BRANCH_NAME="$(git rev-parse --abbrev-ref HEAD)"
# check the branch name is valid or not
if [[ "$BRANCH_NAME" =~ $VALID_BRANCH_REGEX ]]; then
	# Commented lines are for debugging purposes - uncomment if issues occur with this script
  echo "Current branch name is valid: ${BRANCH_NAME}"
  # pwd
  # ADD ACTIONS TO OCCUR WHEN BRANCH NAME IS VALID BELOW (test, integrationTest, lint,... ect.)
  ./gradlew clean test integrationTest
else
  echo -e "\n${RED}Pre-commit: Please correct the branch name${NOCOLOR}"
  printf "\nBranch Name not as per the defined rules like:  "
  echo -e "${GREEN}feature, hotfix, bugfix, library, prerelease, release, dev, improvement, hotfix-102, XXXX-1234, XXXX-1234-something\n"
  echo -e "${ORANGE}You cannot push in these branches directly: ${BRANCHES_TO_SKIP[@]}\n"
  echo -e "${ORANGE}Current BRANCH_NAME: ${BRANCH_NAME}"
  echo -e "\n${RED}Oh, please stop. I cannot allow you to commit with your current branch: ${BRANCH_NAME}${NOCOLOR}"
  exit 1;
fi
########################################################################################################################
# END Check branch name meets expected criteria.
########################################################################################################################
----

Template commit message

----
# Title: Summary, imperative, start upper case, don't end with a period
# No more than 50 chars. #### 50 chars is here:  #
# Remember blank line between title and body.
# Body: Explain *what* and *why* (not *how*). Include task ID (Jira issue).
# Wrap at 72 chars. ################################## which is here:  #
# Special instructions, testing steps, rake, etc
# At the end: Include Co-authored-by for all contributors.
# Include at least one empty line before it. Format:
# Co-authored-by: name <user@users.noreply.github.com>
#
# How to Write a Git Commit Message:
# https://chris.beams.io/posts/git-commit/
#
# 1. Separate subject from body with a blank line
# 2. Limit the subject line to 50 characters
# 3. Capitalize the subject line
# 4. Do not end the subject line with a period
# 5. Use the imperative mood in the subject line
# 6. Wrap the body at 72 characters
# 7. Use the body to explain what and why vs. how:q
----

// Renders correctly in IDE
ifndef::deploy[]
include::../../_includes/eng-level-tooling-not-what-you-were-looking-for.adoc[]
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]
include::{includedir}/eng-level-tooling-not-what-you-were-looking-for.adoc[]
endif::[]

== Reference

* https://www.hostinger.com/tutorials/how-to-use-git-hooks/#How_to_Use_Local_Hooks
* https://www.gitkraken.com/blog/husky-git-hooks
* https://levelup.gitconnected.com/what-are-git-hooks-161a98b09368
* https://githooks.com
* https://github.com/git/git/blob/master/templates/hooks--commit-msg.sample
* https://github.com/git/git/blob/master/templates/hooks--prepare-commit-msg.sample
* https://github.com/git/git/blob/master/templates/hooks--pre-commit.sample
* https://medium.com/@nicklee1/prepending-your-git-commit-messages-with-user-story-ids-3bfea00eab5a
* https://dev.to/aliartiza75/add-git-branch-name-to-each-commit-2a2i
* https://stackoverflow.com/questions/5894946/how-to-add-gits-branch-name-to-the-commit-message
* https://stackoverflow.com/questions/3462955/putting-git-hooks-into-a-repository
* https://itnext.io/using-git-hooks-to-enforce-branch-naming-policy-ffd81fa01e5e
* https://github.com/aitemr/awesome-git-hooks/blob/master/pre-commit/pre-commit-swiftlint
* https://dev.to/abbeyperini/git-commit-message-template-in-terminal-and-vs-code-326p
* https://alex-wasik.medium.com/create-a-custom-git-commit-template-84468232a459
* https://gist.github.com/lisawolderiksen/a7b99d94c92c6671181611be1641c733
* https://mincong.io/2019/07/23/prepare-commit-message-using-git-hook/
* https://stackoverflow.com/questions/38230400/is-there-a-way-to-programmatically-add-some-default-message-to-git-commit
* https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks
* https://www.linkedin.com/pulse/integrating-jira-git-hook-automate-validation-commit-candido-guedes/
* https://guywaldman.com/posts/git-hooks
* https://github.com/aitemr/awesome-git-hooks/blob/master/pre-commit/pre-commit-swiftlint
* https://dev.to/algodame/git-hooks-the-powerful-tool-youre-probably-not-using-but-should-be-1lec
* https://dev.to/akdevcraft/git-pre-hook-pre-commit-with-gradle-task-134m
* https://github.com/gtramontina/ghooks.gradle
* https://guywaldman.com/posts/git-hooks
* https://stackoverflow.com/questions/591923/make-git-automatically-remove-trailing-white-space-before-committing
* https://git-scm.com/book/sv/v2/Customizing-Git-Git-Configuration
* https://gist.github.com/mokagio/0fbf7d475c9326e30edd

* https://medium.com/slalom-build/pre-commit-hooks-for-terraform-9356ee6db882
* https://githooks.com
* https://gatlenculp.medium.com/effortless-code-quality-the-ultimate-pre-commit-hooks-guide-for-2025-57ca501d9835
* https://github.com/aitemr/awesome-git-hooks
* https://github.com/CompSciLauren/awesome-git-hooks
* https://medium.com/@sixpeteunder/automating-code-formatting-with-git-hooks-7ef2af1202d8





