= Test
// Not sure how placement will affect publishing to Confluence
:toc: left

The intent of this page is to collect all the various testing types applied to a product during development as well as
any additional requirements for said testing.

== Gradle: General Test Configuration

All testing should be configured using the native https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html[Gradle test suite]
functionality (https://blog.gradle.org/introducing-test-suites[Intro documentation]). This allows us
to reduce the use of third-party plugins as well as easily configure additional test source sets outside of the basic
unit test set which is preconfigured. Additionally, this also allows for test set specific dependencies, i.e. integration
requires dependencies not required by unit and allows us to further reduce each build component size.

[source, groovy]
----
testing {
    suites {
        configureEach {
            useJUnitJupiter()
            dependencies {
            ...
            }
        }
        test {...}
        integrationTest(JvmTestSuite) {
            testType = TestSuiteType.INTEGRATION_TEST
            sources {
                java {
                    srcDirs = ['src/integration/java']
                }
                resources {
                    srcDirs = ['src/integration/resources']
                }
            }

            targets {
            ...
            }
        }
        apiSmokeTest {...}
    }
}
----

== Test Retry

By including the `org.gradle.test-retry` plugin (GitHub project here) we can easily extend our test configuration to
automatically retry any flakey tests a pre-determined number of times.

=== Add the plugin

[source, groovy]
----
plugins {
    ...
    id "org.gradle.test-retry"                              version "$testRetryPlugin"                  // https://plugins.gradle.org/plugin/org.gradle.test-retry
    ...
}
----

=== Configuration

[source, groovy]
----
targets {
    all {
        testTask.configure {
            ...
            retry {
                maxRetries = 2
                maxFailures = 20
                failOnPassedAfterRetry = true
            }
        }
    }
}
----

== Maven: General Test Configuration TODO

== Not what you were looking for?

=== Testing
* link:testing-unit.adoc[Unit]
* link:testing-integration.adoc[Integration]
* link:testing-thintegration.adoc[Thintegration]
* link:testing-load.adoc[Load]
* link:testing-api-smoke.adoc[API / Smoke]

=== Data Generation

* link:../engineering/development/data/data.adoc[Data]
* link:../engineering/development/data/data-makers.adoc[Data: Makers]

=== Logging

* link:testing-logging-codebuild.adoc[Logging: CodeBuild]



