= Create Approval Rules Template with CloudFormation or Serverless Framework
// Creates the table of contents - this value could be removed and passed in as an attribute from the build task BUT
// having the :toc: value in the adoc files is required for publishToConfluence to work correctly
// Not sure how placement will affect publishing to Confluence
ifndef::confluence[]
:toc: left
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::confluence[]
:toc:

include::{includedir}/version-control-warning.adoc[]
endif::[]

I found references to this being possible to create under Serverless / CloudFormation with the following ...

[source, yaml]
----
# Approval Rule Template
twoApprovalsToMergeApprovalRuleTemplate:
  Type: AWS::CodeCommit::ApprovalRuleTemplate
  Properties:
    ApprovalRuleTemplateName: TwoApprovalsToMergeApprovalRule
    ApprovalRuleTemplateDescription: Require 2 approvals to merge the pr
    ApprovalRuleContent:
      RuleContent:
        Type: Approvers
        Approvers:
          - ProjectAdmin
    RepositoryNames:
      - serverless-resource-templates
      - lambda-utils
      - lambda-layers-shared-services
      - lambda-publishing-callback
      - lambda-token-generator
----

Unfortunately, that does not seem to actual work and throws an invalid cloud formation error. I found some reference to
this here - https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/329


// Renders correctly in IDE
ifndef::deploy[]
include::../../../../_includes/ops-iac-examples-nwywlf.adoc[]
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]
include::{includedir}/ops-iac-examples-nwywlf.adoc[]
endif::[]






