= Create Notification Rules with CloudFormation or Serverless Framework
// Creates the table of contents - this value could be removed and passed in as an attribute from the build task BUT
// having the :toc: value in the adoc files is required for publishToConfluence to work correctly
// Not sure how placement will affect publishing to Confluence
ifndef::confluence[]
:toc: left
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::confluence[]
:toc:

include::{includedir}/version-control-warning.adoc[]
endif::[]

When something is a common part of setup is best to code that action into an easy repeatable step. We want to have
notifications for any PRs that happen against the repositories and since Aws requires that this be coded for each individual repository this has been configured as part of the account setup infrastructure.

[source, yaml]
----
repoNotification:
  Type: AWS::CodeStarNotifications::NotificationRule
  Properties:
    Name: ${self:custom.repoAcct}-lambda-repo-notification-rule
    DetailType: FULL
    Resource: !Sub arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:lambda-name
    EventTypeIds: # https://docs.aws.amazon.com/dtconsole/latest/userguide/concepts.html#concepts-api
      - codecommit-repository-comments-on-pull-requests
      - codecommit-repository-approvals-status-changed
      - codecommit-repository-pull-request-created
      - codecommit-repository-pull-request-merged
    Targets: # IMPORTANT!!! Please be aware that Slack channel must already exist or THIS WILL FAIL!!!
      - TargetType: AWSChatbotSlack
        TargetAddress: !Sub arn:aws:chatbot::${AWS::AccountId}:chat-configuration/slack-channel/${self:custom.repoAcct}
----

Additional EventTypeIds (i.e. things you may want to event on) can be found https://docs.aws.amazon.com/dtconsole/latest/userguide/concepts.html#concepts-api[here].

[WARNING]
In order to execute these Serverless/CloudFormation scripts a Aws Chatbot MUST previously have been configured.




// Renders correctly in IDE
ifndef::deploy[]
include::../../../../_includes/ops-iac-examples-nwywlf.adoc[]
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]
include::{includedir}/ops-iac-examples-nwywlf.adoc[]
endif::[]









