= Naming Conventions
// Creates the table of contents - this value could be removed and passed in as an attribute from the build task BUT
// having the :toc: value in the adoc files is required for publishToConfluence to work correctly
:toc:

// Tags created on pages with keywords relevant to content - default values are present and can be overridden by passed in attribute (and should be). Additionally, when using the publishToConfluence plugin it is more difficult to pass in the keywords so the defaults are preferred.
:keywords: team, naming, conventions


The goal of this page is to capture why things are named as they are along with the reasoning behind it.

Where possible and it makes sense for naming repositories and top level items we want names like the following

== Naming Convention - REQUIRED

Enforcing naming convention ensures DPD repos are easy to find in GitHub and repo scope easily understood.

rc-brr-x-y-z

i.e. <organization>-<team>-<project>-<service or library name>

=== Application Services or Libraries

rc-brr-<project name>-<service or library name>

Example: rc-brr-authorization; rc-brr-tailored

=== Application Infrastructure

rc-brr-<project name>-infrastructure

Example: rc-brr-infrastructure

=== Application Manifests (For Kubernetes)

rc-brr-<project name>-manifests

Example: rc-brr-manifests

== Property Naming Convention

Aws System Manager Properties should follow the following naming convention ...

/<business-area>/<team>/<account/env>/<tech-framework>/<property-name>

example: /rc/brr/dev/tf/slack_brr_dev_aws_dp_alerts_channel_id


== Not what you were looking for?







