= Ticket Template - Story
// Creates the table of contents - this value could be removed and passed in as an attribute from the build task BUT
// having the :toc: value in the adoc files is required for publishToConfluence to work correctly
ifndef::confluence[]
:toc: left
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::confluence[]
:toc:
endif::[]

// Tags created on pages with keywords relevant to content - default values are present and can be overridden by passed in attribute (and should be). Additionally, when using the publishToConfluence plugin it is more difficult to pass in the keywords so the defaults are preferred.
:keywords: build, documentation, top, level, integrated, data, services

// Renders correctly in IDE for testing purposes
// ifndef::confluence[]
// include::../_includes/version-control-warning.adoc[]
// endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::confluence[]
include::{includedir}/version-control-warning.adoc[]
endif::[]

== Description

Description field should include area of work and a one line description of the work

[ FRONTEND | BACKEND | DB | UI | TEST ONLY | RECOVERY ACTION ] This store is responsible for doing X

== Acceptance Criteria

[CAUTION]
Number of specified acceptance criteria is somewhat arbitrary and can be adjusted upon experience

All acceptance criteria should be written in the *Given / When / Then / And* format. If a ticket has more than 5 acceptance criteria that is a good indicator that a ticket is to large and should be further broken down.

Whenever a ticket has more than a single _and_ statement, then each _and_ should be considered as its own test (i.e. given/when/then/and/and/and counts as 3 unique test cases that are written as a single acceptance criteria)

[CAUTION]
This should be written in such a way that even if it is the only part of the story that someone bothers to read that the functionality would be correct and complete.

[NOTE]
Optimally, acceptance criteria should be reviewed by both the BA and QA prior to a dev picking up the story. If they have not been reviewed it is the Devs responsibility for setting up a quick meeting with the BA and QA to review before he starts work.

== Story

A human-readable version of the acceptance criteria i.e. the business case for the functionality.

== Resources

Tickets should have all the necessary resources attached to them. This can be through linking to a technical spec and or individually attached resources. Resources include but are not limited to the following …

* If a ticket involves connecting to communicating with another team/application it is the ticket creators responsibility (probably the BA) to reach out to the other team and request connection details. This includes postmans, instructions to authenticate, a list of all the various environments, any restrictions.
* Who to reach out to for questions
* Who to reach out to for any usernames or passwords
* Test data
** At a minimum a success case, and a fail case


// Renders correctly in IDE
ifndef::deploy[]
include::../../_includes/team-nwywlf.adoc[]
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]
include::{includedir}/team-nwywlf.adoc[]
endif::[]



