= How To: Configure Metrics Filter Alarm
// Not sure how placement will affect publishing to Confluence
ifndef::confluence[]
:toc: left
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::confluence[]
:toc:

include::{includedir}/version-control-warning.adoc[]
endif::[]

This page is to instruct on how to enable an alarm once other metrics are in place.

// Renders correctly in IDE
ifndef::deploy[]

[NOTE]
Please be aware that this page contains similar content to link:aws-configure-dlq-alarm.adoc[How To: Configure DLQ Alarm]
but has some variations.

== Using Serverless

Adding an alarm into a previous Metric Filter configuration is pretty straight forward. Using the
link:aws-configure-metric-filters.adoc[How To: Configure Metric Filters] as our starting point

endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]

[NOTE]
Please be aware that this page contains similar content to {tl-how-to-link-007}[How To: Configure DLQ Alarm]
but has some variations.

== Using Serverless

Adding an alarm into a previous Metric Filter configuration is pretty straight forward. Using the
{tl-how-to-link-008}[How To: Configure Metric Filters] as our starting point

endif::[]

In your `serverless-resource.yml` file add the following.

- an alert topic
- a subscription to the alert topic
- an alarm

----
resources:
    ...
    Resources:
        # An SNS topic to receive alerts
      receivingDevAlertTopic:
        Type: AWS::SNS::Topic
        Condition: CreateQueueNpResources
        Properties:
            TopicName: ${self:custom.appShortName}-topic-dev-alert

        ...

        # A subscription from the previously declared topic to another resource to receive alerts
      receivingDevAlertSubscription:
        Type: AWS::SNS::Subscription
        Condition: CreateQueueNpResources                           # Conditionally create
        Properties:
            Endpoint: https://global.sns-api.chatbot.amazonaws.com  # Aws Slack Chatbot url
            Protocol: https
            TopicArn: !Ref receivingDevAlertTopic                   # Topic declared above

        ...

        # Alarm configured for a specific metric sending to a specific topic
      devWarningsAlarm:
            Type: AWS::CloudWatch::Alarm
      Condition: CreateQueueNpResources                           # Conditionally create
        Properties:
            AlarmName: ldr-service-dev-warnings-alarm             # Name of the alarm
            Namespace: ldr-service-dev-metrics          `         # previously declared metric space
            MetricName: ldr-service-dev-warn                      # Name of previously declared metric filter
            Statistic: Sum
            Period: 10
            EvaluationPeriods: 1
            Threshold: 1
            ComparisonOperator: GreaterThanOrEqualToThreshold
            TreatMissingData: missing
            AlarmActions:
              - !Ref receivingDevAlertTopic                       # What topic to alert to
----


== Reference



// Renders correctly in IDE
ifndef::deploy[]
include::../../../_includes/training-how-to-nwywlf.adoc[]
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]
include::{includedir}/training-how-to-nwywlf.adoc[]
endif::[]


