= How To: Access Secrets Manager
ifndef::confluence[]
:toc: left
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::confluence[]
:toc:
endif::[]

The goal of this page is to cover the various ways that secrets manager can be accessed

=== During CI

In order to access secrets manager during the CI process within the `buildspec.yml`  file you can use the following syntax
Please be aware `secrets-manager` block is different than the `variables` block

[CAUTION]
Please be aware the `secrets-manager` block is diffent than the `variables` block.

----
env:                                                 # Environment specific settings
    shell: /bin/bash                                 # Specify what shell to use when executing
    secrets-manager:
        SLS_CERT_PASSWORD_SECRET_KEY: password_val
    variables:
        AUTH_URL
----

=== During Deploy (Serverless)

In order to access secrets manager during the deploy process within the serverless.yml file you can use the following syntax

[WARNING]
Passing in secrets manager values this way will result in a cleartext environment variable being visible under the lambda environment variables

----
custom:                                                # Set custom options / variables for serverless
  serverlessPrefix: 'sls'                              # Short name for serverless
  appShortName: short                                  # Short app name to prefix all policies with the application specific name
  rolePrefix: Short                                    # Prefix role(s) with application specific name
  repoName: lambda-project                             # The repository name that this acts upon
  # Reference: https://sst.dev/chapters/stages-in-serverless-framework.html
  stage: ${opt:stage, self:provider.stage}              # use the --stage CLI option if it exists. If it does not, then use the default stage specified by provider.stage
  envVar:
    SLS_CERT_PASSWORD_SECRET_KEY:
      dev:  ${ssm:/aws/reference/secretsmanager/jks-password}

...

provider:
  name: aws                                             # Selected cloud provider
  runtime: java17                                       # Selected runtime
  ...
  ...
  environment:                                          # Set environment variables - these are available to the application at runtime
    SLS_CERT_PASSWORD_SECRET_KEY:   ${self:custom.envVar.SLS_CERT_PASSWORD_SECRET_KEY.${self:custom.stage}}
----

=== Inside the Lambda

==== Using AWS SDK

* https://docs.aws.amazon.com/code-library/latest/ug/secrets-manager_example_secrets-manager_GetSecretValue_section.html[Aws Documentation]

==== Secret Manager Caching Client

* https://docs.aws.amazon.com/secretsmanager/latest/userguide/retrieving-secrets_cache-java.html[Aws Documentation]

Add the following dependency

----
implementation 'com.amazonaws.secretsmanager:aws-secretsmanager-caching-java:1.0.2'
----

Then you can leverage it as follows

----
package com.amazonaws.secretsmanager.caching.examples;

    import com.amazonaws.services.lambda.runtime.Context;
    import com.amazonaws.services.lambda.runtime.RequestHandler;
    import com.amazonaws.services.lambda.runtime.LambdaLogger;

    import com.amazonaws.secretsmanager.caching.SecretCache;

    public class SampleClass implements RequestHandler<String, String> {

         private final SecretCache cache  = new SecretCache();

         @Override public String handleRequest(String secretId,  Context context) {
             final String secret  = cache.getSecretString(secretId);

            // Use the secret, return success;

        }
    }
----

According to the documentation this is faster than using the AWS SDK as well as cheaper as it reduces the number of
calls to secrets manager. The current understanding is that this will retrieve the password once and cache it for the
life of the lambda / refresh every hour if the lambda is still up.

[TIP]
In experimentation after startup this seems to save an additional 150-200ms



// Renders correctly in IDE
ifndef::deploy[]
include::../../../_includes/training-how-to-nwywlf.adoc[]
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]
include::{includedir}/training-how-to-nwywlf.adoc[]
endif::[]


