= How To: Configure DLQ Alarm
// Not sure how placement will affect publishing to Confluence
ifndef::confluence[]
:toc: left
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::confluence[]
:toc:
endif::[]

This page describes how to programmatically setup a DLQ (Dead Letter Queue) Alarm

// Renders correctly in IDE
ifndef::deploy[]

[CAUTION]
If you are looking for general info on SNS and SQS see link:aws-configure-sns-or-sqs.adoc[How To: Configure SNS or SQS].
Please be aware that this page contains similar content to link:aws-configure-metric-filters-alarm.adoc[How To: Configure Metrics Filters Alarm]
but has some variations.

== Using Serverless

Adding an alarm into a previous link:aws-configure-dlq.adoc[DLQ configuration] is pretty straight forward. Using the
link:aws-configure-dlq.adoc[How To: Configure DLQ] as our starting point

endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]

[CAUTION]
If you are looking for general info on SNS and SQS see {tl-how-to-link-010}[How To: Configure SNS or SQS].
Please be aware that this page contains similar content to {tl-how-to-link-009}[How To: Configure Metrics Filters Alarm]
but has some variations.

== Using Serverless

Adding an alarm into a previous {tl-how-to-link-006}[DLQ configuration] is pretty straight forward. Using the
{tl-how-to-link-006}[How To: Configure DLQ] as our starting point

endif::[]

In your `serverless-resource.yml` file add the following.

* a queue
* a dlq
* a topic
* and an alert topic

[source, yaml]
----
Resources:                                                      # Resource list
  # Dev SNS/SQS ------------------------------------------------------------------------------------------------------
  receivingDevTopic:
    Type: AWS::SNS::Topic
    Condition: CreateQueueNpResources
    Properties:
      TopicName: ${self:custom.queueName}-topic-dev
  receivingDevAlertTopic:
    Type: AWS::SNS::Topic
    Condition: CreateQueueNpResources
    Properties:
      TopicName: ${self:custom.queueName}-topic-dev-alert
  receivingDevQueueDLQ:                                         # Resource name
    Type: AWS::SQS::Queue                                       # Resource type
    Condition: CreateQueueNpResources                           # Conditionally create
    Properties:                                                 # Resource properties
      QueueName: ${self:custom.queueName}-dev-DLQ               # Name of queue to consume
  receivingDevQueue:                                            # Resource name
    Type: AWS::SQS::Queue                                       # Resource type
    Condition: CreateQueueNpResources                           # Conditionally create
    Properties:                                                 # Resource properties
      QueueName: ${self:custom.queueName}-dev                   # Name of queue to consume
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - receivingDevQueueDLQ
            - Arn
        maxReceiveCount: 3
----

Make sure you set a messaging policy

[CAUTION]
Nothing here is different if you have previously setup the DLQ


[source, yaml]
----
# Messaging Policy -------------------------------------------------------------------------------------------------
snsToReceivingQueueSQSDevPolicy:
  Type: AWS::SQS::QueuePolicy
  Condition: CreateQueueNpResources                           # Conditionally create
  Properties:
    PolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Sid: "allow-sns-messages"
          Effect: "Allow"
          Principal:
            Service:
              - "sns.amazonaws.com"
          Resource:
            Fn::GetAtt:
              - receivingDevQueue
              - Arn
          Action: "SQS:SendMessage"
          Condition:
            ArnEquals:
              "aws:SourceArn":
                Ref: receivingDevTopic
    Queues:
      - Ref: receivingDevQueue
----

Then configure your subscription and add an additional alert subscription.

This is where you set the email that alerts should go to.

[WARNING]
The email address here will receive a confirmation email that must be confirmed before it receiving any alerts.

[source, yaml]
----
# Subscription -----------------------------------------------------------------------------------------------------
receivingDevQueueSubscription:
  Type: 'AWS::SNS::Subscription'
  Condition: CreateQueueNpResources                           # Conditionally create
  Properties:
    TopicArn:
      Fn::Join:
        - ':'
        - - 'arn:aws:sns'
          - Ref: 'AWS::Region'
          - Ref: 'AWS::AccountId'
          - ${self:custom.queueName}-topic-dev
    Endpoint:
      Fn::GetAtt:
        - receivingDevQueue
        - Arn
    Protocol: sqs
    RawMessageDelivery: 'true'
receivingDevAlertSubscription:
  Type: AWS::SNS::Subscription
  Condition: CreateQueueNpResources                           # Conditionally create
  Properties:
    Endpoint: benjamin.rhine@benrhine.com
    Protocol: email
    TopicArn: !Ref receivingDevAlertTopic
----

Then, same as before in your primary `serverless.yml` add onError  to the function

[CAUTION]
Nothing here is different if you have previously setup the DLQ


[source, yaml]
----
functions:
  publishingStatusCallback:
    handler: com.benrhine.lambdapublishingstatuscallback.v1.lambda.aws.handler.PublishingStatusCallbackHandler::handleRequest
    snapStart: true                                     # Improves start time by pre-building and caching an image (CAN NOT be enabled if you want to use provisionedConcurrency)
    events:
      - sqs:                                            # Not preferred way to to do this but the other ways result in
          arn:                                          # 'EventSourceArn.split is not a function' error
            Fn::Join:
              - ':'
              - - arn
                - aws
                - sqs
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - ${self:custom.queueName}-${self:custom.stage}
    onError: arn:aws:sns:us-west-2:npAccountNum:${self:custom.queueName}-topic-${self:custom.stage} # Ref, Fn::GetAtt and Fn::ImportValue are supported as well
----

== Reference

- https://fidelapi.com/blog/how-to-set-up-sqs-dead-letter-queues-with-alarm-notifications/
- https://stackoverflow.com/questions/31326574/amazon-cloudwatch-alarm-not-triggered
- https://mnapoli.fr/sqs-dead-letter-queue-alarm


// Renders correctly in IDE
ifndef::deploy[]
include::../../../_includes/training-how-to-nwywlf.adoc[]
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]
include::{includedir}/training-how-to-nwywlf.adoc[]
endif::[]

