= Configure Git (Quick Start)
ifndef::confluence[]
:toc: left
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::confluence[]
:toc:
endif::[]

To configure git to support both BitBucket and Aws CodeCommit you can use the following file ...

* Linux
** Open Terminal
** Execute `cd ~/` to ensure you are in the User Home directory
** Execute either `vi .gitconfig`  or `vim .gitconfig`
** Paste the file below
** Update helper to `helper = ?`
*** https://stackoverflow.com/questions/53305965/whats-the-best-encrypted-git-credential-helper-for-linux
*** https://techexpertise.medium.com/storing-git-credentials-with-git-credential-helper-33d22a6b5ce7
* MacOS
** Open Terminal / iTerm
** Execute `cd ~/` to ensure you are in the User Home directory
** Execute either `vim .gitconfig`  or if you prefer a more gui experience subl .gitconfig  which will open the file in Sublime Text
** Paste the file below
** Update helper to `helper = osxkeychain`
* Windows
** Open CMD / PowerShell / Git Bash
** Navigate to User Home directory
** IF using Git Bash execute `vi .gitconfig`
** Paste the file below
** Update helper to `helper = wincred`

[CAUTION]
Please ensure that where helper  is declared that it is set correctly to the system that it is configured on

[NOTE]
For more info on Git configuration please see the following
- https://git-scm.com/doc/credential-helpers or https://git-scm.com/docs/gitcredentials

----
[user]
    name = YOUR-NAME
    email = YOUR-EMAIL@company.com
[difftool "sourcetree"]
    cmd = "'' "
[mergetool "sourcetree"]
    cmd = "'' "
    trustExitCode = true
[filter "lfs"]
    required = true
    clean = git-lfs clean -- %f
    smudge = git-lfs smudge -- %f
    process = git-lfs filter-process
[core]
    autocrlf = false
[credential "https://your-company.com"]
    provider = generic
    helper = osxkeychain
[credential "https://git-codecommit.*.amazonaws.com"]
    provider = generic
    helper = !aws --profile=np-pa codecommit credential-helper $@
    UseHttpPath = true
[credential "https://git-codecommit.us-east-2.amazonaws.com/v1/repos/gradle-lambda-template"]
    provider = generic
[credential "https://git-codecommit.us-west-2.amazonaws.com/v1/repos/gradle-lambda-template"]
    provider = generic
[credential]
    helper = osxkeychain
[credential "https://git-codecommit.us-west-2.amazonaws.com/v1/repos/aws-s3-wrapper"]
----

include::../../../_includes/training-how-to-nwywlf.adoc[]

* link:../../engineering/onboarding/howto-configure-git-ssh.adoc[Configure: Git SSH]




