= How To - Publish to Confluence
// Creates the table of contents - this value could be removed and passed in as an attribute from the build task BUT
// having the :toc: value in the adoc files is required for publishToConfluence to work correctly
ifndef::confluence[]
:toc: left
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::confluence[]
:toc:
endif::[]

// Tags created on pages with keywords relevant to content - default values are present and can be overridden by passed in attribute (and should be). Additionally, when using the publishToConfluence plugin it is more difficult to pass in the keywords so the defaults are preferred.
:keywords: how, to, tutorial, documenation, publish, to, confluence, configuration, help

// Renders correctly in IDE for testing purposes
// ifndef::confluence[]
// include::../_includes/version-control-warning.adoc[]
// endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::confluence[]
include::{includedir}/version-control-warning.adoc[]
endif::[]

This How To is intended to describe the complete setup and configuration of https://nomisp.github.io/confluence-publisher-plugin/[publishToConfluence].

Code can be found https://github.com/nomisp/confluence-publisher-plugin[here].

== Why publish your documentation to Confluence?

The biggest reason to publish your documentation to Confluence is that it is industry standard and that is where most people will initially look for your documentation. Additionally, Confluence is a location that most interested parties will have access to as not everyone will always have access to the repository that is containing the documentation.

== Prerequisite

For the `publishToConfluence` plugin to work correctly the `asciidoc` plugin must already be included in your build. To see how to get asciidoc up and running correctly check out {how-to-2-link}[How To - Asciidoc]. However, it is not necessary to do further configuration of `asciidoc` as it is used internally in `publishToConfluence` but `publishToConfluence` WILL FULLY GENERATE ITS OWN VARIANT of documentation to publish that WILL NOT be visible in the `build` folder.

[IMPORTANT]
`publishToConfluence` DOES NOT COPY DOCUMENTATION GENERATED BY ASCIIDOC!!! It generates its own special copy that is not visible in the `build` folder that is published. If a `asciidoc` task is created that has attributes, those attributes need to be supplied to `publishToConfluence` separately.

[CAUTION]
Please be aware that when modeling the structure there should be an associated folder for every top level `adoc` file.
i.e. If you have an `onboarding.adoc` then you should have an `onboarding` folder.

== Suggested documentation structure

Defining a solid documentation structure is 100% critical for this plugin to work smoothly.

Please review {how-to-5-link}[How To - Structure Project Doc as Code]

== How to add publishToConfluence to a project

Find the latest version of the plugin

* https://plugins.gradle.org/plugin/ch.nomisp.confluence.publisher

=== Using Gradle (Preferred)

Start by including the plugin in the Gradle build ...

[source, kotlin]
----
include::../../../../build.gradle.kts[tag=publishToConfluenceImport]
----

Next configure the publishToConfluence plugin ...

=== Configuration Values

* `asciiDocRootFolder = file("documentation")` - Tell the publish plugin where to find the documentation to publish
* `outputDir = "${rootProject.layout.buildDirectory}/docs"` - Where to put the documentation that is being published locally
* `rootConfluenceUrl = "https://benrhine.com/confluence"` - URL that is being published to
* `spaceKey = "RC"` - Base space that is being published to
* `ancestorId = "555555"` - Top level pageId that is being published to
* `notifyWatchers = false` - Notify anyone watching the page
* `orphanRemovalStrategy = OrphanRemovalStrategy.KEEP_ORPHANS` - THE MOST CRITICAL OPTION IN THIS CONFIGURATION, this ensures that if anyone has added pages to confluence that not under version control that they are not removed.
* `restApiVersion = "v1"` - When using an on prem server for Confluence the version should be set to `v1` as `v2` is primarily for cloud instances.
* `versionMessage = "this is a test update"` - Set an update message, in the future this should be the git commit message

=== Configure for On-Prem Confluence

[source, kotlin]
----
include::../../../../build.gradle.kts[tag=confluencePublisher1]
    password = "XXXXXXX"
include::../../../../build.gradle.kts[tag=confluencePublisher2]
----

* `username = ""` - When using an on prem server for Confluence the username should be empty (this is different if using a cloud instance)
* `password = "XXXXXX"` - This should be your {how-to-1-link}[Confluence user PAT (personal access token)] - optimally this would be a service account but have not figured out how to get one for a service account at this point

=== Configure for Cloud Confluence

[source, kotlin]
----
include::../../../../build.gradle.kts[tag=confluencePublisher1]
    password = "XXXXXXX"
include::../../../../build.gradle.kts[tag=confluencePublisher2]
----

* `username = "YOUR-USER@FAKE.COM"` - When using a cloud instance your username is required
* `password = "XXXXXX"` - This should be your {how-to-10-link}[Confluence token that you generated]  - optimally this would be a service account but have not figured out how to get one for a service account at this point

==== Advanced Configuration | Overcoming Limitations

`publishToConfluence` plugin by default will publish/push whatever directory structure has been created under the `asciiDocRootFolder = file("documentation")` and will place that structure underneath whatever `ancestorId` has been specified in the task configuration. If this functionality does not fully support your needs you can add additional custom publishing tasks as follows

[source, kotlin]
----
register<PublishToConfluenceTask>("publishTest") {
    asciiDocRootFolder = file("documentation/app")
    outputDir = "${rootProject.layout.buildDirectory}/docs/app"
    rootConfluenceUrl = "https://benrhine.com/confluence"
    spaceKey = "RC"
    // this is the top level space pageId for Global Data Product
    ancestorId = "55555"
    username = ""
    password = "XXXXXXX"
    notifyWatchers = false
    // THIS MUST ABSOLUTELY BE SET TO KEEP_ORPHANS OR IT WILL DELETE EVERYTHING IN THE SPACE - DO NOT CHANGE!!!
    // Set to ensure if someone creates a page on confluence rather than here it is not lost
    orphanRemovalStrategy = OrphanRemovalStrategy.KEEP_ORPHANS
    // Most server versions are using v1, v2 is primarily cloud
    restApiVersion = "v1"
    versionMessage = "this is a test update"
}
----

The above assumes that you have configured asciidoc to publish to a different location and you now want to publish that documentation to a different location in Confluence with a different `ancestorId`.

[IMPORTANT]
The `orphanRemovalStrategy` should always be set to `OrphanRemovalStrategy.KEEP_ORPHANS`. This will ensure that if anyone has created a page in Confluence manually that is not under version control that it will not be lost.

==== Attributes

If you need to pass attributes to any asciidoc task then they must also be passed to the `publishToConfluence` task. This can be accomplished as follows ...

[source, kotlin]
----
register<PublishToConfluenceTask>("publishTest") {
    //...
    setProperty("attributes", mapOf(
        // "toc" to "", // This value will not set correctly so files MUST have :toc: in them
        "sourcedir"     to file("documentation").absolutePath,
        "includedir"    to file("documentation/_includes").absolutePath,
        "author"        to "test author",    // This value will only be visible in generated doc, Confluence derives author from PAT
        "project-name"  to projectName,      // Dynamically set project name
        "revdate"       to today,            // Update last updated value
        "organization"  to organization      // What organization is this documentation under
    ))
}
----

===== includedir

[TIP]
If the documentation you are publishing has any AsciiDoc include statements present please review the following ...

The `includedir is a special case is a bit funky depending on which system is trying to operate on the AsciiDoc.

* local system / IDE wants a relative path as a provided value like `../_includes`
* building the doc wants the absolute path like `/User/username/repo/doc/_includes`

In order to make this happy in all variations it is suggested that each `adoc` file have the following ...

* `:includedir: ../../_includes` - or whatever the appropriate relative path is. This will ensure the IDE is happy and the preview documentation renders correctly.

It is also suggested that each AsciiDoc task have an `includedir` attribute with the absolute path to the actual `_include` directory like the following ...

[source, kotlin]
----
attributes(
    mapOf(
        "includedir"    to file("documentation/_includes").absolutePath
    )
)
----

This will ensure when the AsciiDoc task is executed that the full and complete paths are present and all includes will be fully rendered in the generated documentation.

==== Execution

[source, shell]
----
./gradlew publishToConfluence
----

or

[source, shell]
----
./gradlew publishToConfluence --stacktrace
----

In this case I recommend including the `--stacktrace` option as it will better inform you if there is a header name conflict that needs tobe addressed rather than just failing.

=== Using Maven

* TODO

== The ancestorId

When publishing documentation that belongs below a given page or is attached to a specific page a `ancestorId` must be provided in order for publishing to work correctly.

This also poses a bit of a chicken-and-egg problem as the page to be attached to must already exist, meaning that you must already have access to the `ancestorId` and have a way to supply it to the Gradle task.

=== Where do you get the ancestorId?

To get the `ancestorId` the simplest way is to go out to Confluence and to manually retrieve the `pageId` that you wish to attach the published page to. In the following example `https://benrhine.net/wiki/spaces/RC/pages/5388370263/How+To+-+Publish+project+specific+to+Confluence` the number following `pages` is the `pageId`. This will be essentially the same regardless of if you are using On-Prem or Cloud based Confluence, you can then supply the `pageId` to the `ancestorId` directly to the Gradle task or through some other means within the build.

However, that is not the best approach. While it is quite likely that _some_ `pageId` 's will be manually specified and hard coded into a projects build for documentation publishing, for known values it is recommended that they be stored as some form or properties for reference by all projects.

== Stored pagedId's and the CI build

In the case of {team-name-1-abv-upper} team, top level Confluence `pageId` 's are stored in Aws System Manager parameter store when xxxx[YYYY] Terraform/OpenTofu subproject is executed. This allows known top level Confluence `pageId` 's to be available to all projects that the {team-name-1-abv-upper} team is working on.

=== Get pageIds from Aws System Manager in a GitHub Action

To retrieve the stored ids, these can be accessed as follows ...

[source, yaml]
----
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v5.0.0
    with:
      aws-region: ${{ secrets.DEV_AWS_REGION }}               # REQUIRED
      role-to-assume: ${{ secrets.CI_ADMIN_ROLE }}                 # REQUIRED
      role-session-name: "${{ github.run_name }}-${{ github.run_id }}-${{ github.run_attempt }}"                      # RECOMMENDED
      role-duration-seconds: ${{ secrets.DEV_ROLE_DURATION }} # 15 mins - this is the minimum allowable duration  # RECOMMENDED
  - name: Retrieve SSM Parameter and set as env var
    uses: dkershner6/aws-ssm-getparameters-action@v2
    with:
      parameterPairs: |
        dev/tf/tfstate_bucket_name             = DEV_TF_TFSTATE_BUCKET_NAME,
        /dev/tf/doc_project_confluence_pat = DOC_PROJECT_CONFLUENCE_PAT,
----

* First authenticate to Aws
* Retrieve the properties and set them as an environment variable

=== Passing retrieved values to Gradle

The retrieved values can then be passed to the Gradle build as follows ...

[source, yaml]
----
  - name: Publish documentation with Gradle
    env:
      HOW_TO_PAGE_ID:             ${{ env.DOC_PROJECT_HOW_TO_PAGE_ID }}
      TUTORIALS_PAGE_ID:          ${{ env.DOC_PROJECT_TUTORIALS_PAGE_ID }}
      TOOLING_PAGE_ID:            ${{ env.DOC_PROJECT_TOOLING_PAGE_ID }}
    run: ./gradlew publishToConfluence --stacktrace
----

=== Using values from GitHub Actions in Gradle build

and they can be accessed in the Gradle build as follows ...

[source, kotlin]
----
val confluenceTeamPageId = System.getenv("TEAM_PAGE_ID")
val confluenceTeamBusinessPageId = System.getenv("BUSINESS_PAGE_ID")
----

== Expected Warnings

You should expect to see a number of warnings when running `publishToConfluence`

[source, shell]
----
> Task :publishToConfluence
(unknown):0: warning: already initialized constant org.jruby.gen::InterfaceImpl518332989
(unknown):0: warning: already initialized constant org.jruby.gen::InterfaceImpl518332989
(unknown):0: warning: already initialized constant org.jruby.gen::InterfaceImpl518332989
(unknown):0: warning: already initialized constant org.jruby.gen::InterfaceImpl518332989
...
----

Additionally, you should expect to see the following ...

[source, shell]
----
Deprecated Gradle features were used in this build, making it incompatible with Gradle 10.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
----

Which if you run the suggested command will result in ...

[source, shell]
----
╰ ./gradlew publishToConfluence --warning-mode all                                                                                                                                   24.0.2+12-FR 

> Configure project :
The StartParameter.isConfigurationCacheRequested property has been deprecated. This is scheduled to be removed in Gradle 10. Please use 'configurationCache.requested' property on 'BuildFeatures' service instead. Consult the upgrading guide for further information: https://docs.gradle.org/9.0.0/userguide/upgrading_version_8.html#deprecated_startparameter_is_configuration_cache_requested

----

This item `StartParameter.isConfigurationCacheRequested` is part of the plugin is not something we have control over so we just have to hope this is updated in the plugin prior to Gradle v10 release.

== Troubleshooting

If the documentation fails to publish check for the following ...

* New pages have duplicate titles
** This will fail and will not clearly tell you that this is what happens but titles must be unique in Confluence

=== Errors

==== No Label Found

This error is a quite odd one that I ran into by chance, and it is not super clear from the error itself what is occurring. In short when publishing the publishing task is attempting to delete a label that does not exist. Why that label does not exist is unclear, someone may have added a label and then removed it again outside the publishing process. As with all other statements in the documentation it is strongly recommended to only make changes to pages that are version controlled in their home repository.

[source, shell]
----
> Task :publishToConfluence FAILED
(unknown):0: warning: already initialized constant org.jruby.gen::InterfaceImpl883794868
Publishing to Confluence failed: Could not publish page 'Engineering'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishToConfluence'.
> Publishing to Confluence failed

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to generate a Build Scan (Powered by Develocity).
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':publishToConfluence'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:135)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:288)
        ...
Caused by: java.lang.RuntimeException: Could not publish page 'Engineering'
        ...
Caused by: org.sahli.asciidoc.confluence.publisher.client.http.RequestFailedException: No label found : favourite (request: DELETE https://benrhine.com/confluence/rest/api/content/274181636/label?name=favourite <empty body>, response: 404  {"statusCode":404,"data":{"authorized":false,"valid":true,"allowedInReadOnlyMode":true,"errors":[],"successful":false},"message":"No label found : favourite","reason":"Not Found"}, reason: <none>)
        ...
----

===== Fix

There are several potential fixes for this error.

====== Manual

Simply go to the page in question and add the label that is not found, refresh the page, run the publish command again

====== Build

If you're having consistent problems with this error you can either run publish with the following option ...

[source, shell]
----
./gradlew publishToConfluence --skipLabelSync
----

or you can add it permanently in the build ...

[source, kotlin]
----
confluencePublisher {
    // your existing config...
    skipLabelSync.set(true)
}
----

I think either of the above are a bit questionable as it is important to understand why the label went away, especially if you can't trace down any edits in the Confluence page history. I think it better to attempt to re-add the missing label and fix the execution and then re-add anything if it's missing.

== Recommendations

As your documentation grows it can be a challenge to keep it updated, especially if the Confluence URLs changing. To simplify updates it is recommended to create a `substitution-values.adoc` file in the `_includes` directory. This file should include all values to be substituted in your doc and to create a unified location for updating semi-dynamic values.

It will look similar to the following example

[source, asciidoc]
----
:project-name:                      base-cloud-infrastructure
:project-link:                      https://benrhine.com
:project-repo:                      https://benrhine.com
:project-adr-link:                  https://benrhine.com
:project-tech-spec-link:            https://benrhine.com

...

----

These values can then be used throughout the documentation.

[TIP]
Providing the values here will ensure the documentation renders correctly within the IDE.

In addition, to ensure these dynamic values are substituted correctly and do not get stale it is also recommended that these values be passed in as part of the `asciiDocAttributes` map to override the values in the `substitution-values.adoc` file.

[source, kotlin]
----
// include::../../../../build.gradle.kts[tag=confluencePublisher3]
----


== Reference

* https://nomisp.github.io/confluence-publisher-plugin/
* https://www.google.com/search?q=gradle+register+custom+confluencePublisher+task&oq=gradle+register+custom+confluencePublisher+task&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIJCAEQIRgKGKABMgkIAhAhGAoYoAEyCQgDECEYChigATIHCAQQIRiPAtIBCDk3ODFqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8
*


// Renders correctly in IDE
ifndef::deploy[]
include::../../../_includes/training-how-to-nwywlf.adoc[]
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]
include::{includedir}/training-how-to-nwywlf.adoc[]
endif::[]

