= Data: Company wide meta data

This is page where I muse about what metadata that I believe all data objects should have and why.

== Base Metadata

There is always some debate about storing to much information and additional costs associated with doing so, but I am of
the opinion that not being willing to spend the small additional amount to always include the following fields will cost
more in the long run due to not being able to query or audit the data as needed or an attempt to add most of these values
at a later date will result in a much greater effort. I believe that the following fields are mandatory and are the minimum audit data
that should be available for every object in the database.

|===
|Metadata Field |Reasoning

|archived
|Adds ability to hide data from query

|createDate
|Should always be able to track when data was created

|updateDate
|Should always be able to track when data was updated

|createUser
|Should always be able to track who (or what) created the data

|updateUser
|Should always be able to track who (or what) updated the data

|version
|How many times has this record been touched

|transactionGroupId (Optional - depends on db type)
|Track if this record was created as part of a group of transactions; associate record with larger actions in the database

|tenantId (Optional - depends on db type)
|More relevant to NoSQL dbs

|id
|Every record should have a unique id

|type
|What type of data is this? Prod? Test? Test Purgeable? Test Persistent?

|purgeable
|Can this data be removed?
|===

=== Data Cleanup

The better understand how data cleanup works see link:../data/data-cleanup.adoc[Data: Cleanup]. Data cleanup works by
leveraging a comination of the `archived`, `type`, and `purgeable` fields.

=== Data Type

link:data-type.adoc[Data: Types]

== Interim Metadata

Interim metadata is data that may be required on multiple objects but not all objects.

|===
|Metadata Field |Reasoning

|Some field that is selectively required
|This field may be required on multiple objects but not all objects
|===






