= (Step 1) - Domain Deployment

This step is crucial to keeping your serverless deployments organized and to ensuring that the resources necessary are
available for all other serverless deployments in a given region.

== Corresponding build steps

Example build steps

* Link build step here
* Link build step here

[NOTE]
Be aware that role names should not be changed unless absolutely necessary. If a role name changes *ALL* CodeBuild
processes that use work based off this repository will need to be updated. See or link:../../../../engineering/how-to/aws-codebuild-after-recreating-resources.adoc[How To: Fix Aws CodeBuild after
recreating resources] or link:sls-troubleshooting.adoc[Troubleshooting]. If names are not changed CodeBuild process should remember the previously attached role and should not need to be edited.

== Requirements

To successfully run this deploy and remove you *MUST* supply the buildspec with a role that has admin privilege's. It is
unfortunately not possible to create the roles necessary without having a predefined role to start with. Currently, this
builds using the "codebuild-admin-role" which may need updated. Once this deploy has been ran all further serverless deploys can operate with roles that they define.

== What does this deploy do?
This repo is intended to hold the very first steps of IaC (Infrastructure as Code) necessary for all Serverless deploys.
At the time of writing (20230622) this currently has three main functions ...

* creates an Admin IAM role that will be leveraged by all future Serverless deploys
** Note: All IAM roles are created in a Global context
** This has a single "AdministratorAccess" policy attached
* creates a CodeBuild IAM role that will be leveraged by the application resource deploys
** Note: All IAM roles are created in a Global context
** This should have 8 policies attached (This can be important when troubleshooting)
* creates a default S3 deployment bucket to keep S3 organized and from running over the too many buckets issue
** Bucket creation is *Regional*
** If the top level bucket does not exit it will be created
** All serverless deploys ran in a given region will then create their deployment folders under this one organized folder
** All buckets created will have AES256 encryption by default (and this is no extra charge as of early 2023 - see https://docs.aws.amazon.com/AmazonS3/latest/userguide/default-bucket-encryption.html[here])
** All buckets created will deny public access to the bucket and objects by default
** Sets max number of old deployments to keep to 10

[WARNING]
Be aware this deployment is NOT idempotent!!! What is meant by this statement is you can absolutely run this deploy multiple
times and it will complete successfully BUT if you have manually modified the infrastructure post deploy it will not modify
those changes back to their original state without being fully removed and re-deployed. ie. if you remove a ACL from the
role and then run the deploy again it WILL NOT re-add the policy to that role.

=== Executing Deploy

To run this deploy go here and click "Start build".

[WARNING]
This deploy should only be executed by someone who understand what is going on in this deploy as this may affect all other
Serverless deploys in a region.

=== Post Deploy State

* There should be two roles created
* admin role should have the following policies
* build-deploy role should have the following policies
* a bucket should be created
* the bucket should contain a "serverless" directory

== Additional steps post deploy (optional)

If your application requires a certificate create an additional "certificates" folder in the new bucket. Unfortunately,
this can not be automated at this time. Once you have created the certificates folder upload your cert to the new bucket.

== Removing this deploy

Running the reverse of the deploy should only be executed by someone who truly understands the ramification of removing
these resources. This will remove required IAM roles and generated deployment resources from other Serverless deployments that they depend upon.

=== Executing Deploy

To run this deploy go here and click "Start build".

[WARNING]
This deploy should only be executed by someone who understand what is going on in this deploy as this WILL affect all
other serverless deploys in a region. Executing this deploy will remove REQUIRED roles and resources.

=== Post Remove State

After running removal the IAM roles will no longer be present and the "serverless" folder within the created bucket will be gone.

[NOTE]
Do note that the top level bucket will still exist unless you delete in manually and it will still contain any additional
items that were manually created post deploy.

== Examples

=== Admin User Policy
.Click here to expand ...
[%collapsible]
====
[source, yaml]
----
resources:                                              # Specify all resources below
  Resources:                                            # Resource list
    codebuildAdminRole:                                 # Resource name
      Type: AWS::IAM::Role                              # Resource type
      Properties:                                       # Resource properties
        RoleName: ${self:custom.serverlessPrefix}-domain-admin-role
        AssumeRolePolicyDocument:                       # Role Configuration
          Version: '2012-10-17'                         # When aws built their default policy
          Statement:
            - Effect: Allow
              Principal:
                AWS:
                  - Fn::Join:
                      - ':'
                      - - 'arn:aws:iam'
                        - ''
                        - Ref: 'AWS::AccountId'
                        - root
              Action: sts:AssumeRole
        ManagedPolicyArns:                              # Managed policies to attach to new role
          - arn:aws:iam::aws:policy/AdministratorAccess
----
====

=== CodeBuild User Policy
.Click here to expand ...
[%collapsible]
====
[source, yaml]
----
resources:                                              # Specify all resources below
  Resources:                                            # Resource list
    codebuildResourceServiceRole: # Resource name
      Type: AWS::IAM::Role                              # Resource type
      Properties: # Resource properties
        Path: /service-role/                            # If you want a custom resource path
        # required if you want to use 'serverless deploy --function' later on
        RoleName: ${self:custom.serverlessPrefix}-domain-codebuild-build-deploy-resources-service-role
        AssumeRolePolicyDocument: # Role Configuration
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - codebuild.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:custom.serverlessPrefix}-log-resource-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow # note that these rights are given in the default policy and are required if you want logs out of your lambda(s)
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:TagResource
                  Resource:
                    - 'arn:aws:logs:*:*:*'
          - PolicyName: ${self:custom.serverlessPrefix}-logs-resource-build-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:TagResource
                  Resource:
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:logs'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - log-group:/aws/codebuild/${self:custom.serverlessPrefix}-resources
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:logs'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - log-group:/aws/codebuild/${self:custom.serverlessPrefix}-resources:*
          - PolicyName: ${self:custom.serverlessPrefix}-s3-resource-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - s3:PutObject
                    - s3:GetObject
                    - s3:GetObjectVersion
                    - s3:GetBucketAcl
                    - s3:GetBucketLocation
                    - s3:PutAccelerateConfiguration
                  Resource:
                    - arn:aws:s3:::sls-regional-domain-deploy
                    - arn:aws:s3:::sls-regional-domain-deploy/*
          - PolicyName: ${self:custom.serverlessPrefix}-codecommit-resource-repo-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - codecommit:GitPull
                  Resource:
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:codecommit'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - ${self:custom.repoName}
          - PolicyName: ${self:custom.serverlessPrefix}-codecommit-resource-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - codecommit:GitPull
                  Resource:
                    - '*'
          - PolicyName: ${self:custom.serverlessPrefix}-codebuild-resource-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - codebuild:CreateReportGroup
                    - codebuild:CreateReport
                    - codebuild:UpdateReport
                    - codebuild:BatchPutTestCases
                    - codebuild:BatchPutCodeCoverages
                  Resource:
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:codebuild'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - report-group/${self:custom.serverlessPrefix}-resources-*
          - PolicyName: ${self:custom.serverlessPrefix}-resource-iam-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - iam:PassRole
                  Resource:
                    - '*'
          - PolicyName: ${self:custom.serverlessPrefix}-resource-assume-role-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - sts:AssumeRole
                  Resource:
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:iam'
                          - ''
                          - Ref: 'AWS::AccountId'
                          - role/${self:custom.serverlessPrefix}-domain-admin-role
----
====

=== Bucket Creation

By including the serverless-deployment-bucket plugin and defining deploymentBucket.name and giving it a value
(under provider) you have just instructed the deploy to use or in the case it does not exist create a new s3 bucket. A
few important notes

* `serverSideEncryption` - it does not seem that aws respects any other value than AES256 at this time
* `blockPublicAccess` (under provider) this option is deny by default so is not required BUT to clearly understand what it does, this is deny ONLY for the bucket, this will not set the block public access checkmark when signed into aws console.
* `blockPublicAccess`  (under custom.deploymentBucket) this option WILL set the block all public access checkmark. This is a plugin option and is required in order to deny all public access to the created bucket and children items.
* `accelerate` (under custom.deploymentBucket) this option is supposed to enable accelerated uploads and does enable it in s3 but I have yet to see this actually be beneficial
* `maxPreviousDeploymentArtifacts`  set the max number of build artifacts to retain

.Click here to expand ...
[%collapsible]
====
[source, yaml]
----
########################################################################################################################
# Update Section: ONLY UPDATE HERE!!!
########################################################################################################################
custom:                                                 # Set custom options / variables for serverless
  serverlessPrefix: 'sls'                               # Short name for serverless
  repoName: serverless-resource-templates               # The repository name that this acts upon
  # Reference: https://sst.dev/chapters/stages-in-serverless-framework.html
  stage: ${opt:stage, self:provider.stage}              # use the --stage CLI option if it exists. If it does not, then use the default stage specified by provider.stage
  deploymentBucket: # used by serverless-deployment-bucket
    accelerate: true
    blockPublicAccess: true
########################################################################################################################
# End Update Section
########################################################################################################################
frameworkVersion: '3'                                   # Set what version of serverless is being used
plugins:
  - serverless-deployment-bucket
service: ${self:custom.serverlessPrefix}-domain-resources  # This should match the application name specified in the settings.gradle
  # Additionally, to the matching name add "-resources". If the service
  # name is not distinct, the resources will be removed when the application
# is un-deployed.
provider:
  name: aws                                             # Selected cloud provider
  stage: ${opt:stage, 'dev'}                            # Uses user specified stage (--stage VALUE) or defaults to dev
  region: ${opt:region, 'us-west-2'}                    # Uses user specified region (--region VALUE) or defaults to `us-west-2`
  logRetentionInDays: 30                                # Set log retention
  deploymentBucket: # Collect all serverless deployment files in a single bucket
    name: ${self:custom.serverlessPrefix}-regional-domain-deploy               # Specify bucket name
    serverSideEncryption: AES256                        # Specify bucket encryption
    maxPreviousDeploymentArtifacts: 10 # Max number of old builds to keep
    # This DOES NOT deny public access for all sub items only the bucket, to Deny All set blockPublicAccess under custom
    # blockPublicAccess: false
----
====

== References

* https://docs.aws.amazon.com/AmazonS3/latest/userguide/default-bucket-encryption.html
* https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml#deployment-bucket
* https://www.serverless.com/plugins/serverless-deployment-bucket
* https://serverlessfirst.com/create-iam-deployer-roles-serverless-app/ easoning for this type of role setup
* https://michaeltimbs.me/blog/creating-a-serverless-deploy-user/
* https://www.serverless.com/framework/docs/providers/aws/guide/resources




