= Serverless: (AWS) Create CodeBuild job
:toc:

[CAUTION]
Please be aware that to be able to create a CodeBuild job using IaC the executing role
will require the CodeBuild IAM permission (see link:sls-aws-create-codebuild-job.adoc#_permissions_required[Permissions Required]

[NOTE]
Be aware this process is exactly the same as link:../aws/aws-cf-create-codepipeline.adoc[CloudFormation: (AWS) Create CodeBuild job]
*_EXCEPT_* CloudFormation only has a single `Resources` block. It does not require the additional `resources` block that
Serverless uses.

[NOTE]
To view details on CodeBuild see link:../../../../engineering/cloud/infrastructure/aws/aws-setup-code-build.adoc[Setup: CodeBuild]


.serverless.yml
[source, yaml]
----
resources:
    Resources:
      CbDisasterRecoverySyncRepository:
        Type: AWS::CodeBuild::Project
        DependsOn: ServiceCodeBuildServiceRole
        Properties:
          Name: !Sub ${ProjectName}-disaster-recovery-sync
          Description: Syncs CodeCommit repository to alternate region
          BadgeEnabled: !Ref BuildBadge
          Source:
            Type: !Sub ${GitSourceType}
            Location: !Sub https://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/${GitRepoName}
            BuildSpec: .codebuild/buildspec-replicate.yml
          SourceVersion: !Ref GitSourceVersion
          Environment:
            Type: !Sub ${EnvType}
            ComputeType: !Sub ${EnvComputeType}
            Image: !Sub ${EnvImage}
          ServiceRole: !Sub ${ServiceCodeBuildServiceRole.Arn}
          Artifacts:
            Type: NO_ARTIFACTS
          LogsConfig:
            CloudWatchLogs:
              Status: !Ref CloudWatchLogs
              GroupName: !Sub ${ProjectName}-disaster-recovery-sync
            S3Logs:
              Status: !Ref S3Logs
----

== Permissions Required

[WARNING]
Look at example repo for actual policies; I know the below is not complete but is necessary in order for this to work. It
is intended to reflect that additional work is required in order to make everything flow correctly.

[CAUTION]
Other permissions may be required to fully execute, but below is _close_ to a minimum set of permissions to
allow for deployment.

[source, shell]
----
statement {
    actions   = [
      "codebuild:CreateReportGroup",
      "codebuild:CreateReport",
      "codebuild:UpdateReport",
      "codebuild:BatchPutTestCases",
      "codebuild:BatchPutCodeCoverages",
      "codebuild:StartBuild",
      "codebuild:StopBuild",
      "codebuild:RetryBuild"
    ]
    resources = ["*"]
    effect = "Allow"
  }
----

== Not what you were looking for?

* link:../../../../engineering/cloud/infrastructure/aws/aws-setup-code-build.adoc[Setup: CodeBuild]
* link:../../../../engineering/cloud/infrastructure/aws/aws-setup-code-pipeline.adoc[Setup: CodePipeline]
* link:../aws/aws-cf-create-codebuild-job.adoc[CloudFormation: (AWS) Create CodeBuild job]
* link:../terraform/tf-aws-create-codebuild-job.adoc[Terraform: (AWS) Create CodeBuild job]
* link:../aws/aws-cf-create-codepipeline.adoc[CloudFormation: (AWS) Create CodePipeline]
* link:../serverless/sls-aws-create-codepipeline.adoc[Serverless: (AWS) Create CodePipeline]
* link:../terraform/tf-aws-create-codepipeline.adoc[Terraform: (AWS) Create CodePipeline]

