= Serverless: (AWS) Create CloudWatch Insight Query
// Creates the table of contents - this value could be removed and passed in as an attribute from the build task BUT
// having the :toc: value in the adoc files is required for publishToConfluence to work correctly
// Not sure how placement will affect publishing to Confluence
ifndef::confluence[]
:toc: left
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::confluence[]
:toc:

include::{includedir}/version-control-warning.adoc[]
endif::[]

[CAUTION]
Please be aware that to be able to save a Log Insight Query using IaC the executing role
will require the `logs:PutQueryDefinition` IAM permission.

// Renders correctly in IDE
ifndef::deploy[]

[NOTE]
Be aware this process is exactly the same as link:../aws/aws-cf-create-cloudwatch-insight-query.adoc[CloudFormation: (AWS) Create CloudWatch Insight Query]
*_EXCEPT_* CloudFormation only has a single `Resources` block. It does not require the additional `resources` block that
Serverless uses.

[NOTE]
To view suggested pre-defined queries see link:../../../../engineering/tooling/tooling-cloud-aws/tooling-aws-cloudwatch-insights-json.adoc[CloudWatch Insights for JSON logs]

endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]

[NOTE]
Be aware this process is exactly the same as {sl-ops-link-003-001-003}[CloudFormation: (AWS) Create CloudWatch Insight Query]
*_EXCEPT_* CloudFormation only has a single `Resources` block. It does not require the additional `resources` block that
Serverless uses.

[NOTE]
To view suggested pre-defined queries see {tl-tooling-link-022-006}[CloudWatch Insights for JSON logs]

endif::[]

.serverless.yml
[source, yaml]
----
resources:
	Resources:
    # Pre-defined Log Insights Queries ---------------------------------------------------------------------------------
    generalFindAllDebugQueryDefinition:
      Type: AWS::Logs::QueryDefinition
      Properties:
        Name: "general-find-all-debug"
        QueryString: 'DEBUG'
    generalFindAllInfoQueryDefinition:
      Type: AWS::Logs::QueryDefinition
      Properties:
        Name: "general-find-all-info"
        QueryString: 'INFO'
    generalFindAllWarningsQueryDefinition:
      Type: AWS::Logs::QueryDefinition
      Properties:
        Name: "general-find-all-warnings"
        QueryString: 'WARNING'
    generalFindAllErrorsQueryDefinition:
      Type: AWS::Logs::QueryDefinition
      Properties:
        Name: "general-find-all-errors"
        QueryString: 'ERROR'
    generalFindAllAwsXrayQueryDefinition:
      Type: AWS::Logs::QueryDefinition
      Properties:
        Name: "general-find-all-aws-xray"
        QueryString: 'AWS_XRAY'
    generalFindAllJsonDebugQueryDefinition:
      Type: AWS::Logs::QueryDefinition
      Properties:
        Name: "general-find-all-json-debug"
        QueryString: 'fields @timestamp, @message, @logStream, @log | filter level = "WARN" | sort @timestamp desc | limit 20'
    generalFindAllJsonInfoQueryDefinition:
      Type: AWS::Logs::QueryDefinition
      Properties:
        Name: "general-find-all-json-info"
        QueryString: 'fields @timestamp, @message, @logStream, @log | filter level = "INFO" | sort @timestamp desc | limit 20'
    generalFindAllJsonWarningsQueryDefinition:
      Type: AWS::Logs::QueryDefinition
      Properties:
        Name: "general-find-all-json-warnings"
        QueryString: 'fields @timestamp, @message, @logStream, @log | filter level = "WARN" | sort @timestamp desc | limit 20'
    generalFindAllJsonErrorsQueryDefinition:
      Type: AWS::Logs::QueryDefinition
      Properties:
        Name: "general-find-all-json-errors"
        QueryString: 'fields @timestamp, @message, @logStream, @log | filter level = "ERROR" | sort @timestamp desc | limit 20'
    generalFindAllJsonColdStartTrueQueryDefinition:
      Type: AWS::Logs::QueryDefinition
      Properties:
        Name: "general-find-all-json-cold-start-true"
        QueryString: 'fields @timestamp, @message, @logStream, @log | filter coldStart = "true" | sort @timestamp desc | limit 20'
    generalFindAllJsonColdStartFalseQueryDefinition:
      Type: AWS::Logs::QueryDefinition
      Properties:
        Name: "general-find-all-json-cold-start-false"
        QueryString: 'fields @timestamp, @message, @logStream, @log | filter coldStart = "false" | sort @timestamp desc | limit 20'
----



// Renders correctly in IDE
ifndef::deploy[]
include::../../../../_includes/ops-iac-serverless-nwywlf.adoc[]
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]
include::{includedir}/ops-iac-serverless-nwywlf.adoc[]
endif::[]


