= Serverless: (AWS) Create CodeBuild job
// Creates the table of contents - this value could be removed and passed in as an attribute from the build task BUT
// having the :toc: value in the adoc files is required for publishToConfluence to work correctly
// Not sure how placement will affect publishing to Confluence
ifndef::confluence[]
:toc: left
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::confluence[]
:toc:

include::{includedir}/version-control-warning.adoc[]
endif::[]


// Renders correctly in IDE
ifndef::deploy[]

[CAUTION]
Please be aware that to be able to create a CodeBuild job using IaC the executing role
will require the CodeBuild IAM permission (see link:sls-aws-create-codebuild-job.adoc#_permissions_required[Permissions Required]

[NOTE]
Be aware this process is exactly the same as link:../aws/aws-cf-create-codepipeline.adoc[CloudFormation: (AWS) Create CodeBuild job]
*_EXCEPT_* CloudFormation only has a single `Resources` block. It does not require the additional `resources` block that
Serverless uses.

[NOTE]
To view details on CodeBuild see link:../../../../engineering/tooling/tooling-cloud-aws/tooling-aws-setup-code-build.adoc[Setup: CodeBuild]

endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]

[CAUTION]
Please be aware that to be able to create a CodeBuild job using IaC the executing role
will require the CodeBuild IAM permission (see {sl-ops-link-003-004-002}#_permissions_required[Permissions Required]

[NOTE]
Be aware this process is exactly the same as {sl-ops-link-003-001-005}[CloudFormation: (AWS) Create CodeBuild job]
*_EXCEPT_* CloudFormation only has a single `Resources` block. It does not require the additional `resources` block that
Serverless uses.

[NOTE]
To view details on CodeBuild see {tl-tooling-link-022-021}[Setup: CodeBuild]

endif::[]

.serverless.yml
[source, yaml]
----
resources:
    Resources:
      CbDisasterRecoverySyncRepository:
        Type: AWS::CodeBuild::Project
        DependsOn: ServiceCodeBuildServiceRole
        Properties:
          Name: !Sub ${ProjectName}-disaster-recovery-sync
          Description: Syncs CodeCommit repository to alternate region
          BadgeEnabled: !Ref BuildBadge
          Source:
            Type: !Sub ${GitSourceType}
            Location: !Sub https://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/${GitRepoName}
            BuildSpec: .codebuild/buildspec-replicate.yml
          SourceVersion: !Ref GitSourceVersion
          Environment:
            Type: !Sub ${EnvType}
            ComputeType: !Sub ${EnvComputeType}
            Image: !Sub ${EnvImage}
          ServiceRole: !Sub ${ServiceCodeBuildServiceRole.Arn}
          Artifacts:
            Type: NO_ARTIFACTS
          LogsConfig:
            CloudWatchLogs:
              Status: !Ref CloudWatchLogs
              GroupName: !Sub ${ProjectName}-disaster-recovery-sync
            S3Logs:
              Status: !Ref S3Logs
----

== Permissions Required

[WARNING]
Look at example repo for actual policies; I know the below is not complete but is necessary in order for this to work. It
is intended to reflect that additional work is required in order to make everything flow correctly.

[CAUTION]
Other permissions may be required to fully execute, but below is _close_ to a minimum set of permissions to
allow for deployment.

[source, shell]
----
statement {
    actions   = [
      "codebuild:CreateReportGroup",
      "codebuild:CreateReport",
      "codebuild:UpdateReport",
      "codebuild:BatchPutTestCases",
      "codebuild:BatchPutCodeCoverages",
      "codebuild:StartBuild",
      "codebuild:StopBuild",
      "codebuild:RetryBuild"
    ]
    resources = ["*"]
    effect = "Allow"
  }
----

// Renders correctly in IDE
ifndef::deploy[]
include::../../../../_includes/ops-iac-serverless-nwywlf.adoc[]
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]
include::{includedir}/ops-iac-serverless-nwywlf.adoc[]
endif::[]

