= Terraform: (AWS) Create CodeBuild job
// Creates the table of contents - this value could be removed and passed in as an attribute from the build task BUT
// having the :toc: value in the adoc files is required for publishToConfluence to work correctly
// Not sure how placement will affect publishing to Confluence
ifndef::confluence[]
:toc: left
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::confluence[]
:toc:

include::{includedir}/version-control-warning.adoc[]
endif::[]


// Renders correctly in IDE
ifndef::deploy[]

[CAUTION]
Please be aware that to be able to create a CodeBuild job using IaC the executing role
will require the CodeBuild IAM permission (see link:tf-aws-create-codebuild-job.adoc#_permissions_required[Permissions Required]

[NOTE]
To view details on CodeBuild see link:../../../../engineering/tooling/tooling-cloud-aws/tooling-aws-setup-code-build.adoc[Setup: CodeBuild]

endif::[]

// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]

[CAUTION]
Please be aware that to be able to create a CodeBuild job using IaC the executing role
will require the CodeBuild IAM permission (see {sl-ops-link-003-005-002}#_permissions_required[Permissions Required]

[NOTE]
To view details on CodeBuild see {tl-tooling-link-022-021}[Setup: CodeBuild]

endif::[]

== CodeBuild Job

.module main.tf
[source, shell]
----
resource "aws_codebuild_project" "codebuild_job" {
  name          = var.build_name
  description   = var.build_description
  build_timeout = var.build_timeout
  service_role  = var.service_role_arn    # Should be passed in via module declaration
  badge_enabled = var.build_badge_enabled       # Defaulted to true in variables.tf

# Depends on should be specified in root module main.tf module declaration
#   depends_on = [
#     var.service_role_arn
#   ]

  artifacts {
    type = var.artifacts  # Defaulted to true in variables.tf
  }

  environment {
    compute_type                = var.env_compute_type  # Defaulted to true in variables.tf
    image                       = var.env_image # Defaulted to true in variables.tf
    type                        = var.env_type  # Defaulted to true in variables.tf
    image_pull_credentials_type = var.env_image_pull_credentials_type # Defaulted to true in variables.tf
  }

  logs_config {
    cloudwatch_logs {
      status      = var.cloudwatch_logs #enabled # Defaulted to true in variables.tf
      group_name  = var.build_name
    }

    s3_logs {
      status   = var.s3_logs # disabled
    }
  }

  source {
    type            = var.git_source_type
    location        = var.git_repo_location
    buildspec       = var.git_repo_buildspec
    git_clone_depth = var.git_clone_depth # 0 Represents a full checkout which is necessary for git commands

    git_submodules_config {
      fetch_submodules = var.git_fetch_submodules
    }
  }

  source_version = var.git_source_version

  tags = {
    environment = var.env_tags_environment
    origination = var.env_tags_origination
  }
}
----

[TIP]
Use the above as an example and copy/paste into a Terraform script and edit the values to suit your purpose.

=== Using a Terraform module to create a CodeBuild job

The preceding Terraform snippet is part of a re-usable module, and the module can be declared in the `main.tf` as follows ...

.main.tf

[source, shell]
----
module "build_domain_resources_disaster_recovery" {
  source                        = "../modules/codebuild"                                   # Where to find the module
  ######################################################################################################################
  build_name                    = "tf_${var.project_name}_disaster_recovery_sync"            # Custom defined value
  build_description             = "Syncs CodeCommit repository to alternate region"       # Custom defined value
  service_role_arn              = module.codebuild_service_role.created_role_arn          # Value retrieved from module outputs.tf
  git_repo_name                 = var.git_repo_name                                       # Value passed in via variables.tf
  git_repo_location             = "https://git-codecommit.${data.aws_region.current.name}.amazonaws.com/v1/repos/${var.git_repo_name}" # Custom defined value
  git_repo_buildspec            = ".codebuild/buildspec-replicate.yml"
  env_tags_environment          = var.tag_environment_tools                                 # Value passed in via variables.tf
  env_tags_origination          = var.tag_origination_repo
  env_tags_project              = var.project_name

# ALL COMMENTED VALUES HAVE REASONABLE DEFAULT VALUES ASSIGNED IN variables.tf
#   build_timeout               = 5                                     # Value is defaulted in module variables.tf only set here if overriding
#   build_badge_enabled         = true                                  # Value is defaulted in module variables.tf only set here if overriding
#   git_source_type             = "CODECOMMIT"                          # Value is defaulted in module variables.tf only set here if overriding
#   git_source_version          = "refs/heads/main"                     # Value is defaulted in module variables.tf only set here if overriding
#   git_repo_buildspec          = ".codebuild/buildspec-replicate.yml"  # Value is defaulted in module variables.tf only set here if overriding
#   git_clone_depth             = 0                                     # Value is defaulted in module variables.tf only set here if overriding
#   git_fetch_submodules        = false                                 # Value is defaulted in module variables.tf only set here if overriding
#   artifacts                   = "NO_ARTIFACTS"                        # Value is defaulted in module variables.tf only set here if overriding
#   env_type                    = "LINUX_CONTAINER"                     # Value is defaulted in module variables.tf only set here if overriding
#   env_compute_type            = "BUILD_GENERAL1_SMALL"                # Value is defaulted in module variables.tf only set here if overriding
#   env_image                   = "aws/codebuild/standard:7.0"          # Value is defaulted in module variables.tf only set here if overriding
#   env_image_pull_credentials_type = "CODEBUILD"                       # Value is defaulted in module variables.tf only set here if overriding
#   cloudwatch_logs             = "ENABLED"                             # Value is defaulted in module variables.tf only set here if overriding
#   s3_logs                     = "DISABLED"                            # Value is defaulted in module variables.tf only set here if overriding

  # codebuild module instantiation depends on the following modules; resources in modules declared within "depends_on"
  # must complete instantiation prior to codebuild instantiation.
  depends_on = [
    module.codebuild_service_role
  ]
}
----

== Permissions Required

[WARNING]
Look at example repo for actual policies; I know the below is not complete but is necessary in order for this to work. It
is intended to reflect that additional work is required in order to make everything flow correctly.

[CAUTION]
Other permissions may be required to fully execute, but below is _close_ to a minimum set of permissions to
allow for deployment.

[source, shell]
----
statement {
    actions   = [
      "codebuild:CreateReportGroup",
      "codebuild:CreateReport",
      "codebuild:UpdateReport",
      "codebuild:BatchPutTestCases",
      "codebuild:BatchPutCodeCoverages",
      "codebuild:StartBuild",
      "codebuild:StopBuild",
      "codebuild:RetryBuild"
    ]
    resources = ["*"]
    effect = "Allow"
  }
----

// Renders correctly in IDE
ifndef::deploy[]
include::../../../../_includes/ops-iac-terraform-nwywlf.adoc[]
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]
include::{includedir}/ops-iac-terraform-nwywlf.adoc[]
endif::[]