= Terraform: (AWS) Create System Property/Parameter

[CAUTION]
System Manager properties/parameter can be either GLOBAL _or_ REGIONAL. By Default properties _are_ regional. Additionally,
Aws has recently introduced "Cross-account" parameter sharing ... see https://aws.amazon.com/blogs/mt/introducing-parameter-store-cross-account-sharing/[here].

[NOTE]
To view details on System Manager Parameters/Properties, see link:../../../../engineering/cloud/infrastructure/aws/aws-system-parameters.adoc[System Parameters]

[TIP]
System Manager properties/parameter are Aws Free Tier eligible for _Standard parameters_. If you need to secure parameters
 within the System manager, there will be a fee (see https://aws.amazon.com/systems-manager/pricing/[here]).

== System Manager Property/Parameter

.module main.tf
[source, shell]
----
resource "aws_ssm_parameter" "create_system_manager_property" {
  name          = var.property_name
  description   = var.property_description
  type          = var.property_type
  data_type     = var.property_data_type
  value         = var.property_value

  tags = {
    environment = var.property_tags_environment
  }
}
----

[TIP]
Use the above as an example and copy/paste into a Terraform script and edit the values to suit your purpose.

=== Using a Terraform module to create Properties/Parameters

The preceding Terraform snippet is part of a re-usable module and the module can be declared in the `main.tf` as follows ...

.main.tf
[source, shell]
----
module "ssm_1" {
    source                    = "./modules/ssm"                                 # Where to find the module
    ####################################################################################
    property_name             = "tf.brr.tools.build.s3.bucket.name"            # Custom defined value
    property_description      = "Deployment bucket created by domain-resources" # Custom defined value
    property_value            = module.s3.aws_s3_bucket.bucket                  # Value retrieved from module outputs.tf
    property_tags_environment = var.environment_tag                             # Value passed in via variables.tf
}
----

[NOTE]
To see how variables are declared and setup within Terraform please review link:../terraform/tf-variables.adoc[Terraform: Variables]

For each additional property declared in CloudFormation or Serverless it requires and additional resource block (ie copy/paste
and change values). Whereas depending on requirements Terraform can perform creation within a loop ...

.main.tf
[source, shell]
----
variable "ssm_objects_to_create" {
  type = list(object({
    name            = string
    description     = string
    type            = string  # This value is defaulted in ssm module variables
    data_type       = string  # This value is defaulted in ssm module variables
    value           = string
    tag_environment = string
  }))
  default = [
    {
      name            = "tf.brr.tools.build.s3.bucket.name"
      description     = "Deployment bucket created by domain-resources"
      type            = "String"  # This value is defaulted
      data_type       = "text"    # This value is defaulted
      value           = "test" #module.s3.aws_s3_bucket.bucket
      tag_environment = "tools"
    },
    {
      name            = "tf.brr.tools.build.s3.legacy.bucket.name"
      description     = "Deployment bucket created by deprecated sls-domain-resources-deploy"
      type            = "String"  # This value is defaulted
      data_type       = "text"    # This value is defaulted
      value           = "sls-cross-account-shared-services-domain-deploy"
      tag_environment = "tools"
    },
  ]
}

module "ssm" {
  for_each = { for inst in var.ssm_objects_to_create : inst.name => inst }
  source                        = "./modules/ssm"   # Where to find the module
  property_name                 = each.value.name
  property_description          = each.value.description
  property_value                = each.value.value  # In order to use a value from a previous module the value must be exported in outputs.tf
  property_tags_environment     = each.value.tag_environment
}
----





// Renders correctly in IDE
ifndef::deploy[]
include::../../../../_includes/ops-iac-terraform-nwywlf.adoc[]
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]
include::{includedir}/ops-iac-terraform-nwywlf.adoc[]
endif::[]


