= Terraform: (AWS) Create CloudWatch Insight Query
// Creates the table of contents - this value could be removed and passed in as an attribute from the build task BUT
// having the :toc: value in the adoc files is required for publishToConfluence to work correctly
// Not sure how placement will affect publishing to Confluence
ifndef::confluence[]
:toc: left
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::confluence[]
:toc:

include::{includedir}/version-control-warning.adoc[]
endif::[]

[CAUTION]
Please be aware that to be able to save a Log Insight Query using IaC the executing role
will require the `logs:PutQueryDefinition` IAM permission.

// Renders correctly in IDE
ifndef::deploy[]

[NOTE]
To view suggested pre-defined queries see link:../../../../engineering/tooling/tooling-cloud-aws/tooling-aws-cloudwatch-insights-json.adoc[CloudWatch Insights for JSON logs]

endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]

[NOTE]
To view suggested pre-defined queries see {tl-tooling-link-022-006}[CloudWatch Insights for JSON logs]

endif::[]

== CloudWatch Insights

.module main.tf
[source, shell]
----
resource "aws_cloudwatch_query_definition" "create_cloudwatch_query" {
  name            = var.query_name
  log_group_names = var.query_log_group_names
  query_string    = var.query
}
----

[TIP]
Use the above as an example and copy/paste into a Terraform script and edit the values to suit your purpose.

=== Using a Terraform module to create CloudWatch Insight queries

The preceding Terraform snippet is part of a re-usable module, and the module can be declared in the `main.tf` as follows ...

.main.tf
[source, shell]
----
module "cloudwatch_queries_tools" {
  providers = {
    aws = aws.ddsc-tools
  }
  source      = "../modules/cloudwatch-query"
  for_each    = { for inst in var.cloudwatch_queries_to_create : inst.name => inst}
  query_name  = each.value.name
  query       = each.value.value
}
----

// Renders correctly in IDE
ifndef::deploy[]

[NOTE]
To see how variables are declared and setup within Terraform please review link:../terraform/tf-variables.adoc[Terraform: Variables]

endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]

[NOTE]
To see how variables are declared and setup within Terraform please review {sl-ops-link-003-005-019}[Terraform: Variables]

endif::[]


// Renders correctly in IDE
ifndef::deploy[]
include::../../../../_includes/ops-iac-terraform-nwywlf.adoc[]
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]
include::{includedir}/ops-iac-terraform-nwywlf.adoc[]
endif::[]




