= Terraform: (AWS) Create DynamoDB table

// Renders correctly in IDE
ifndef::deploy[]

[WARNING]
As discussed for Cloudformation link:../aws/aws-cf-create-dynamo-table.adoc[here] and Serverless link:../serverless/sls-aws-create-dynamo-table.adoc[here],
it is possible to create dynamo tables with a `DeletionPolicy` to protect data from being removed during the deploy / undeploy
process. _HOWEVER_, this is not possible when using Terraform. This is the one major drawback I have noted in migrating
previous work to Terraform as in order to protect database tables it is a much more significant effort if it is even
possible at all.

[CAUTION]
For DynamoDB access to be successful the application using the table must be running with a role that has a minimum `dynamodb`
access policy as defined under link:tf-aws-create-dynamo-table.adoc#_permissions_required[permissions required].

[NOTE]
To view details on DynamoDB, see link:../../../../engineering/tooling/tooling-cloud-aws/tooling-aws-dynamodb.adoc[Aws: DynamoDB]

endif::[]

// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]

[WARNING]
As discussed for Cloudformation {sl-ops-link-003-001-006}[here] and Serverless {sl-ops-link-003-004-004}[here],
it is possible to create dynamo tables with a `DeletionPolicy` to protect data from being removed during the deploy / undeploy
process. _HOWEVER_, this is not possible when using Terraform. This is the one major drawback I have noted in migrating
previous work to Terraform as in order to protect database tables it is a much more significant effort if it is even
possible at all.

[CAUTION]
For DynamoDB access to be successful the application using the table must be running with a role that has a minimum `dynamodb`
access policy as defined under {sl-ops-link-003-005-004}#_permissions_required[permissions required].

[NOTE]
To view details on DynamoDB, see {tl-tooling-link-022-010}[Aws: DynamoDB]

endif::[]

[TIP]
DynamoDB has a free tier and provides 25GB of storage, along with 25 provisioned Write and 25 provisioned Read Capacity
Units (WCU, RCU) which is enough to handle 200M requests per month
(see https://aws.amazon.com/dynamodb/pricing/[here]).


== Permissions Required

Minimum required permissions set to be attached to the role that is being used to execute the application in order for
it to be able to access DynamoDB.

[source, yaml]
----
  - PolicyName: ${self:custom.appShortName}-dynamo-policy
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - { "Fn::GetAtt": [ "PersonsDynamoDBTable", "Arn" ] }
----



// Renders correctly in IDE
ifndef::deploy[]
include::../../../../_includes/ops-iac-terraform-nwywlf.adoc[]
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]
include::{includedir}/ops-iac-terraform-nwywlf.adoc[]
endif::[]















