= Terraform: (AWS) Create CodePipeline
// Not sure how placement will affect publishing to Confluence
:toc: left

[CAUTION]
Please be aware that to be able to create a CodePipeline job using IaC the executing role
will require the CodePipeline IAM permission (see link:tf-aws-create-codepipeline.adoc#_permissions_required[Permissions Required]

[NOTE]
To view details on CodePipeline see link:../../../../engineering/cloud/infrastructure/aws/aws-setup-code-pipeline.adoc[Setup: CodePipline]

== CodePipeline

.module main.tf
[source, shell]
----

resource "aws_codepipeline" "codepipeline" {
  name     = var.pipeline_name
  role_arn = var.service_role_arn

  artifact_store {
    location = var.deployment_bucket
    type     = var.artifact_store_type
  }

  stage {
    name = var.stage_1_name

    action {
      name             = var.stage_1_action_name
      category         = var.stage_1_action_category
      owner            = var.stage_1_action_owner
      provider         = var.stage_1_action_provider
      version          = var.stage_1_action_version
      output_artifacts = var.stage_1_action_output_artifacts
      namespace        = var.stage_1_action_namespace

      configuration = {
        OutputArtifactFormat = var.stage_1_action_configuration_output_artifact_format
        PollForSourceChanges = var.stage_1_action_configuration_poll_for_source_changes
        RepositoryName = var.git_repo_name
        BranchName       = var.stage_1_action_configuration_branch_name
      }
    }
  }

  stage {
    name = "replicate-to-alternate-region"

    action {
      name             = "replicate"
      category         = "Build"
      owner            = "AWS"
      provider         = "CodeBuild"
      input_artifacts  = ["SourceArtifact"]
      version          = "1"

      configuration = {
        ProjectName = var.codebuild_project
      }
    }
  }

#   stage {
#     name = "Deploy"
#
#     action {
#       name            = "Deploy"
#       category        = "Deploy"
#       owner           = "AWS"
#       provider        = "CloudFormation"
#       input_artifacts = ["build_output"]
#       version         = "1"
#
#       configuration = {
#         ActionMode     = "REPLACE_ON_FAILURE"
#         Capabilities   = "CAPABILITY_AUTO_EXPAND,CAPABILITY_IAM"
#         OutputFileName = "CreateStackOutput.json"
#         StackName      = "MyStack"
#         TemplatePath   = "build_output::sam-templated.yaml"
#       }
#     }
#   }

  tags = {
    environment = var.pipeline_tags_environment
    origination = var.pipeline_tags_origination
  }
}
----

[TIP]
Use the above as an example and copy/paste into a Terraform script and edit the values to suit your purpose.

=== Using a Terraform module to create a CodePipeline

The preceding Terraform snippet is part of a re-usable module, and the module can be declared in the `main.tf` as follows ...

.main.tf
[source, shell]
----
module "pipeline_disaster_recovery" {
  source                        = "../modules/codepipeline"                                # Where to find the module
  ######################################################################################################################
  pipeline_name                 = "${var.project_name}-replication-pipeline"              # Custom defined value
  service_role_arn              = module.codepipeline_service_role.created_role_arn       # Value retrieved from module outputs.tf
  deployment_bucket             = module.s3.aws_s3_bucket.bucket                          # Value retrieved from module outputs.tf
  codebuild_project             = module.build_disaster_recovery.aws_codebuild_project_name             # Value retrieved from module outputs.tf
  git_repo_name                 = var.git_repo_name                                       # Value passed in via variables.tf
  pipeline_tags_environment     = var.tag_environment_tools
  pipeline_tags_origination     = var.tag_origination_repo
  pipeline_tags_project         = var.project_name
# ALL COMMENTED VALUES HAVE REASONABLE DEFAULT VALUES ASSIGNED IN variables.tf
#   artifact_store_type           = "S3"                                # Value is defaulted in module variables.tf only set here if overriding
#   stage_1_name                  = "code-commit-checkout"              # Value is defaulted in module variables.tf only set here if overriding
#   stage_1_action_name           = "Source"                            # Value is defaulted in module variables.tf only set here if overriding
#   stage_1_action_category       = "Source"                            # Value is defaulted in module variables.tf only set here if overriding
#   stage_1_action_owner          = "AWS"                               # Value is defaulted in module variables.tf only set here if overriding
#   stage_1_action_provider       = "CodeCommit"                        # Value is defaulted in module variables.tf only set here if overriding
#   stage_1_action_version        = "1"                                 # Value is defaulted in module variables.tf only set here if overriding
#   stage_1_action_output_artifacts = ["SourceArtifact"]                # Value is defaulted in module variables.tf only set here if overriding
#   stage_1_action_namespace      = "SourceVariables"                   # Value is defaulted in module variables.tf only set here if overriding
#   stage_1_action_configuration_output_artifact_format = "CODE_ZIP"    # Value is defaulted in module variables.tf only set here if overriding
#   stage_1_action_configuration_poll_for_source_changes = false        # Value is defaulted in module variables.tf only set here if overriding
#   stage_1_action_configuration_branch_name = "main"                   # Value is defaulted in module variables.tf only set here if overriding
  # codepipeline module instantiation depends on the following modules; resources in modules declared within "depends_on"
  # must complete instantiation prior to codepipeline instantiation.
  depends_on = [
    module.codepipeline_service_role,
    module.s3,
    module.build_disaster_recovery
  ]
}
----

== Permissions Required

[WARNING]
Look at example repo for actual policies; I know the below is not complete but is necessary in order for this to work. It
is intended to reflect that additional work is required in order to make everything flow correctly.

[CAUTION]
Other permissions may be required to fully execute, but below is _close_ to a minimum set of permissions to
allow for deployment.

[source, shell]
----
statement {
    actions   = [
      "codepipeline:GetPipeline",
      "codepipeline:GetPipelineExecution",
      "codepipeline:StopPipelineExecution",
      "codepipeline:ListPipelineExecutions"
    ]
    resources = ["*"]
    effect = "Allow"
}
----

// Renders correctly in IDE
ifndef::deploy[]
include::../../../../_includes/ops-iac-terraform-nwywlf.adoc[]
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]
include::{includedir}/ops-iac-terraform-nwywlf.adoc[]
endif::[]