= Comparison: Modules
// Creates the table of contents - this value could be removed and passed in as an attribute from the build task BUT
// having the :toc: value in the adoc files is required for publishToConfluence to work correctly
// Not sure how placement will affect publishing to Confluence
ifndef::confluence[]
:toc: left
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::confluence[]
:toc:

include::{includedir}/version-control-warning.adoc[]
endif::[]

There isn't much to say in this section as Terraform Modules are a concept that fairly unique to Terraform. To quickly
summarize a Terraform Module is essentially a code library for infrastructure that can be reused.

Neither CloudFormation nor Serverless Framework support this concept. Not that you can't write scripts that can be parameterized
and copy pasted to different projects for re-use but to my knowledge you can't create and publish a CloudFormation library
that can be picked up through a build tool and I know for certain this can't currently be done in Serverless Framework.

// Renders correctly in IDE
ifndef::deploy[]
include::../../../../_includes/ops-iac-comparison-nwywlf.adoc[]
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]
include::{includedir}/ops-iac-comparison-nwywlf.adoc[]
endif::[]