= Compare: SSM Parameters
:toc:

[NOTE]
Creating resources within both CloudFormation and Serverless Framework are exactly the same. Whenever you create a resource
in Serverless, it is just RAW CloudFormation, Serverless is *only unique* when not creating resources.

== Creating new Parameters/Properties

To create a new SSM Parameter resource using either CloudFormation or Serverless Framework you can add the following to
either your CloudFormation template or your `serverless.yml`

=== CloudFormation / Serverless declaration

[source, yaml]
----
Resources:
    ...
    DeploymentBucketNameProperty:
      Type: AWS::SSM::Parameter
      Properties:
        Name: brr.tools.build.s3.bucket.name
        Description: !Sub Deployment bucket created by ${ProjectName}
        DataType: text
        Tier: Standard
        Type: String
        Value: !Sub ${AccountName}-${AWS::Region}-${S3DeploymentBucket}
        Tags:
          Environment: build
----

=== The equivalent Terraform code is the following ...

.module main.tf
[source, shell]
----
resource "aws_ssm_parameter" "create_system_manager_property" {
  name          = var.property_name
  description   = var.property_description
  type          = var.property_type
  data_type     = var.property_data_type
  value         = var.property_value

  tags = {
    environment = var.property_tags_environment
  }
}
----

The preceding Terraform snippet is part of a re-usable module and can be declared in the `main.tf` as follows ...

.main.tf
[source, shell]
----
module "ssm_1" {
    source                    = "./modules/ssm"                                 # Where to find the module
    ####################################################################################
    property_name             = "tf.brr.tools.build.s3.bucket.name"            # Custom defined value
    property_description      = "Deployment bucket created by domain-resources" # Custom defined value
    property_value            = module.s3.aws_s3_bucket.bucket                  # Value retrieved from module outputs.tf
    property_tags_environment = var.environment_tag                             # Value passed in via variables.tf
}
----

[NOTE]
To see how variables are declared and setup within Terraform please review link:../terraform/tf-variables.adoc[Terraform: Variables]

For each additional property declared in CloudFormation or Serverless it requires and additional resource block (ie copy/paste
and change values). Whereas depending on requirements Terraform can perform creation within a loop ...

.main.tf
[source, shell]
----
variable "ssm_objects_to_create" {
  type = list(object({
    name            = string
    description     = string
    type            = string  # This value is defaulted in ssm module variables
    data_type       = string  # This value is defaulted in ssm module variables
    value           = string
    tag_environment = string
  }))
  default = [
    {
      name            = "tf.brr.tools.build.s3.bucket.name"
      description     = "Deployment bucket created by domain-resources"
      type            = "String"  # This value is defaulted
      data_type       = "text"    # This value is defaulted
      value           = "test" #module.s3.aws_s3_bucket.bucket
      tag_environment = "tools"
    },
    {
      name            = "tf.brr.tools.build.s3.legacy.bucket.name"
      description     = "Deployment bucket created by deprecated sls-domain-resources-deploy"
      type            = "String"  # This value is defaulted
      data_type       = "text"    # This value is defaulted
      value           = "sls-cross-account-shared-services-domain-deploy"
      tag_environment = "tools"
    },
  ]
}

module "ssm" {
  for_each = { for inst in var.ssm_objects_to_create : inst.name => inst }
  source                        = "./modules/ssm"   # Where to find the module
  property_name                 = each.value.name
  property_description          = each.value.description
  property_value                = each.value.value  # In order to use a value from a previous module the value must be exported in outputs.tf
  property_tags_environment     = each.value.tag_environment
}
----

== Retrieving Parameters/Properties

.To retrieve SSM within CloudFormation
[source, yaml]
----
Resources:
  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${AWS::StackName}-launch-template
      LaunchTemplateData:
        ImageId: '{{resolve:ssm:golden-ami:2}}' # CloudFormation get property
        InstanceType: t2.micro
----

* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references-ssm.html[CloudFormation: SSM]

.To retrieve SSM within serverless.yml
[source, yaml]
----
service: ${ssm:/path/to/service/id}-service
provider:
  name: aws
functions:
  hello:
    name: ${ssm:/path/to/service/myParam}-hello # Serverless get property
    handler: handler.hello
----

* https://www.serverless.com/framework/docs/guides/variables/aws/ssm[Serverless: SSM]


.To retrieve SSM within data.tf
[source, shell]
----
data "aws_ssm_parameter" "my_parameter" {
  name = "/my/path/to/my_parameter"
}
----

.Use retrieved property in variables.tf
[source, shell]
----
variable "environment_tag" {
  description = "Name of environment"
  type        = string
  default     = data.aws_ssm_parameter.my_parameter.value
}
----













