= Disaster Recovery
// Creates the table of contents - this value could be removed and passed in as an attribute from the build task BUT
// having the :toc: value in the adoc files is required for publishToConfluence to work correctly
// Not sure how placement will affect publishing to Confluence
// Renders correctly in IDE
ifndef::confluence[]
:toc: left
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::confluence[]
:toc:

include::{includedir}/version-control-warning.adoc[]
endif::[]

:keywords: engineering, disaster, recovery


[cols="60%,40%"]
|===
|This page is intended to cover the top level design of how disaster recovery will work occur for projects that are part of {team-name-1-abv-upper} and will describe several specific scenarios that are designed to be handled. |TODO
|===

== Possible Issues

=== GitHub is down / unavailable

=== Aws Region becomes unavailable

=== Aws Specific solution

To mitigate the possibly of an entire region of Aws becoming unavailable all repositories could be mirrored to a separate region on every push via CodeBuild and CodePipeline. This mirroring is down to the commit, meaning that even the commit hashes will be the same in both repos. This configuration is part of e4ach projects CloudFormation template and the default backup region is us-east-1. In theory this should guarantee access to the source code across regions and allow for the CloudFormation template to quickly re-imported and applications re-deployed in a different region

=== Lost Account Access

Who do you contact?

=== Lost Account

Who do you contact?

== Repositories Covered by these plans

* TODO

== Recovery Actions


== Open Questions

* Is the same type of replication necessary for libraries and layers? Yes
* Should a pipeline be configured in the backup account to deploy the resources on every push so that in the event of a failure the app deployment jobs just have to be run as everything is ready to go? or would this be to much of an additional cost?
* What happens if an app with a custom domain name goes down due to a region being down and we want to redeploy but we can no longer us the same domain as it is now held/reserved elsewhere in aws?

== Individual Project Disaster Recovery Steps

If you are looking for detailed disaster recovery actions for a specific project please navigate to the specific projects disaster recovery page located under {sl-projects-link}[Projects].

== Reference

* https://dev.to/apatil88/replicate-aws-codecommit-repositories-between-regions-using-codebuild-and-codepipeline-5fh1