= Start Here: Onboarding / Setups / Configurations
// Creates the table of contents - this value could be removed and passed in as an attribute from the build task BUT
// having the :toc: value in the adoc files is required for publishToConfluence to work correctly
// Not sure how placement will affect publishing to Confluence
:toc: left

:keywords: engineering, onboarding, start, here, setups, config, configuration

// Renders correctly in IDE for testing purposes
// ifndef::confluence[]
// include::../_includes/version-control-warning.adoc[]
// endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::confluence[]
include::{includedir}/version-control-warning.adoc[]
endif::[]

== Start Here

Information contained within this page or subpages is specific to onboarding, system setup, and/or configurations that are necessary in order to complete your job. This is the top level page and all information that fits the above description should be added as a sub-page here. While system configuration portion is generic and should mostly apply to any developer starting a new position, some aspects of this documentation is written with a {team-name-1-abv-upper} bent.

=== Step 0: {team-name-1-abv-upper} Team (Team Specific)

Please start by reviewing the business Team information https://dat.jeppesen.com/confluence/spaces/GDP/pages/254612550/Team+Home+Page[here] and the https://dat.jeppesen.com/confluence/spaces/GDP/pages/254612544/Development+Details[Development Details].

If you are not part of the {team-name-1-abv-upper} team and are referencing this documentation it is recommended you review you're Team home page.

== Step 1: Configure your system

This will walk you through system configuration and some tool setups

Choose the setup based on the machine you have ...

* {tl-how-to-link-036}[Linux]
* {tl-how-to-link-035}[MacOS]
* {tl-how-to-link-037}[Windows]

== Step 2: Tool configurations

* {tl-how-to-link-043}[Git - Configure SSH]

[TIP]
Please make sure you have configured authorization for your organization as described {tl-how-to-link-043}#GitConfigureSSH-_step_4_authorizing_your_organizationStep4:Authorizingyourorganization[here]. This is critical for being able to push code.

* {tooling-git-5-link}[Git - Configure PAT]

[NOTE]
Until authentication is handled by GitHub Apps you will need a personal and organizational token.

== Step 3: Review Team Practices (Team Specific)

If you are part of the {team-name-1-abv-upper}  team please review the following ...

If you are not part of the {team-name-1-abv-upper} team and are referencing this documentation it is recommended you review you're Team practices page or use the following as helpful suggestions for your team.

// Renders correctly in IDE
ifndef::deploy[]
include::../_includes/repo-level-engineering-not-what-you-were-looking-for.adoc[]
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]
include::{includedir}/repo-level-engineering-not-what-you-were-looking-for.adoc[]
endif::[]



