= Support
// Creates the table of contents - this value could be removed and passed in as an attribute from the build task BUT
// having the :toc: value in the adoc files is required for publishToConfluence to work correctly
// Not sure how placement will affect publishing to Confluence
// Renders correctly in IDE
ifndef::confluence[]
:toc: left
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::confluence[]
:toc:
endif::[]

:keywords: engineering, support, run, books

// Renders correctly in IDE for testing purposes
// ifndef::confluence[]
// include::../_includes/version-control-warning.adoc[]
// endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::confluence[]
include::{includedir}/version-control-warning.adoc[]
endif::[]

[NOTE]
If further help is required please review the individual project Troubleshooting or Disaster Recovery pages located under {sl-projects-link}[Projects]. Example location `Projects -> Repo/Project Name -> Sub-project/Terraform name`

This is the top level container for all support documentation. Any support articles or documentation specifically geared toward supporting the operation of any projects developed by the {team-name-1-abv-upper} team(s) should be published here. This includes but is not limited to the following ...

// Renders correctly in IDE
ifndef::deploy[]
include::../_includes/eng-level-support-links.adoc[]
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]
include::{includedir}/eng-level-support-links.adoc[]
endif::[]

If further help is required please look under the individual projects located at `Projects -> Repo/Project Name -> Sub-project/Terraform name` for specific Troubleshooting or Disaster Recovery information.

[CAUTION]
Pages under "Support" may be published by individual projects. Please review the header note for which repo is executing the publishing.

// Renders correctly in IDE
ifndef::deploy[]
:intellij: intellij
include::../_includes/repo-level-engineering-not-what-you-were-looking-for.adoc[]
endif::[]
// Renders correctly in AsciiDoc Deployment
ifdef::deploy[]
include::{includedir}/repo-level-engineering-not-what-you-were-looking-for.adoc[]
endif::[]




