= Terraform: (AWS) Create CloudWatch Insight Query

[CAUTION]
Please be aware that to be able to save a Log Insight Query using IaC the executing role
will require the `logs:PutQueryDefinition` IAM permission.

[NOTE]
To view suggested pre-defined queries see link:../../cloud/infrastructure/aws/aws-cloudwatch-insights-json.adoc[CloudWatch Insights for JSON logs]

== CloudWatch Insights

.module main.tf
[source, shell]
----
resource "aws_cloudwatch_query_definition" "create_cloudwatch_query" {
  name            = var.query_name
  log_group_names = var.query_log_group_names
  query_string    = var.query
}
----

[TIP]
Use the above as an example and copy/paste into a Terraform script and edit the values to suit your purpose.

=== Using a Terraform module to create CloudWatch Insight queries

The preceding Terraform snippet is part of a re-usable module, and the module can be declared in the `main.tf` as follows ...

.main.tf
[source, shell]
----
module "cloudwatch_queries_tools" {
  providers = {
    aws = aws.ddsc-tools
  }
  source      = "../modules/cloudwatch-query"
  for_each    = { for inst in var.cloudwatch_queries_to_create : inst.name => inst}
  query_name  = each.value.name
  query       = each.value.value
}
----

[NOTE]
To see how variables are declared and setup within Terraform please review link:../terraform/tf-variables.adoc[Terraform: Variables]







